{{ config(tags=["silver"], materialized="table") }}

select
    dataset_source,
    source_partition,
    source_run_id,
    series_id,
    dt,
    location_id,
    product_id,
    region_id,
    org_group_id,
    category_level_1,
    category_level_2,
    category_level_3,
    observed_demand_qty,
    target_semantics,
    coalesce(censor_flag, false) as censor_flag,
    coalesce(target_source, 'observed_sales') as target_source,
    coalesce(label_quality_score, 0.0) as label_quality_score,
    coalesce(usable_for_training_flag, false) as usable_for_training_flag,
    observed_revenue_net,
    observed_discount_amount,
    promo_flag,
    holiday_flag,
    activity_flag,
    observed_stockout_flag,
    coalesce(observed_stockout_available, false) as observed_stockout_available,
    observed_stockout_intensity,
    day_complete_flag,
    calendar_weekday_name,
    calendar_day_of_week,
    calendar_month,
    calendar_year,
    calendar_week_key,
    event_name_1,
    event_type_1,
    event_name_2,
    event_type_2,
    weather_precipitation,
    weather_temperature,
    weather_humidity,
    weather_wind_level,
    silver_run_id
from {{ ref("silver_daily_product_demand_training_candidates") }}
where observed_demand_qty is not null
  and target_semantics is not null
