{{ config(tags=["silver", "demand"], materialized="table") }}

with unioned as (
    select
        10 as source_priority,
        dataset_source,
        source_partition,
        source_run_id,
        series_id,
        dt,
        location_id,
        product_id,
        region_id,
        org_group_id,
        category_level_1,
        category_level_2,
        category_level_3,
        observed_demand_qty,
        observed_demand_missing_flag,
        observed_demand_parse_error_flag,
        target_semantics,
        target_semantics_raw,
        target_semantics_parse_error_flag,
        censor_flag,
        target_source,
        label_quality_score,
        label_quality_missing_flag,
        label_quality_parse_error_flag,
        usable_for_training_flag,
        usable_for_training_missing_flag,
        censor_flag_missing_flag,
        observed_revenue_net,
        observed_discount_amount,
        promo_flag,
        holiday_flag,
        activity_flag,
        observed_stockout_flag,
        observed_stockout_available,
        observed_stockout_available_missing_flag,
        observed_stockout_intensity,
        day_complete_flag,
        calendar_weekday_name,
        calendar_day_of_week,
        calendar_month,
        calendar_year,
        calendar_week_key,
        event_name_1,
        event_type_1,
        event_name_2,
        event_type_2,
        weather_precipitation,
        weather_temperature,
        weather_humidity,
        weather_wind_level,
        silver_run_id,
        source_name,
        source_policy_id,
        source_file_path,
        source_loaded_at,
        data_origin
    from {{ ref("silver_bakery_daily_product_demand") }}

    union all

    select
        20 as source_priority,
        dataset_source,
        source_partition,
        source_run_id,
        series_id,
        dt,
        location_id,
        product_id,
        region_id,
        org_group_id,
        category_level_1,
        category_level_2,
        category_level_3,
        observed_demand_qty,
        observed_demand_missing_flag,
        observed_demand_parse_error_flag,
        target_semantics,
        target_semantics_raw,
        target_semantics_parse_error_flag,
        censor_flag,
        target_source,
        label_quality_score,
        label_quality_missing_flag,
        label_quality_parse_error_flag,
        usable_for_training_flag,
        usable_for_training_missing_flag,
        censor_flag_missing_flag,
        observed_revenue_net,
        observed_discount_amount,
        promo_flag,
        holiday_flag,
        activity_flag,
        observed_stockout_flag,
        observed_stockout_available,
        observed_stockout_available_missing_flag,
        observed_stockout_intensity,
        day_complete_flag,
        calendar_weekday_name,
        calendar_day_of_week,
        calendar_month,
        calendar_year,
        calendar_week_key,
        event_name_1,
        event_type_1,
        event_name_2,
        event_type_2,
        weather_precipitation,
        weather_temperature,
        weather_humidity,
        weather_wind_level,
        silver_run_id,
        source_name,
        source_policy_id,
        source_file_path,
        source_loaded_at,
        data_origin
    from {{ ref("silver_synthetic_foodservice_daily_product_demand") }}
),
normalized as (
    select
        cast(dataset_source as varchar) as dataset_source,
        cast(source_partition as varchar) as source_partition,
        cast(source_run_id as varchar) as source_run_id,
        cast(series_id as varchar) as series_id,
        cast(dt as date) as dt,
        cast(location_id as varchar) as location_id,
        cast(product_id as varchar) as product_id,
        cast(region_id as varchar) as region_id,
        cast(org_group_id as varchar) as org_group_id,
        cast(category_level_1 as varchar) as category_level_1,
        cast(category_level_2 as varchar) as category_level_2,
        cast(category_level_3 as varchar) as category_level_3,
        try_cast(observed_demand_qty as double) as observed_demand_qty,
        coalesce(try_cast(observed_demand_missing_flag as boolean), false) as observed_demand_missing_flag,
        coalesce(try_cast(observed_demand_parse_error_flag as boolean), false) as observed_demand_parse_error_flag,
        cast(target_semantics as varchar) as target_semantics,
        cast(target_semantics_raw as varchar) as target_semantics_raw,
        coalesce(try_cast(target_semantics_parse_error_flag as boolean), false) as target_semantics_parse_error_flag,
        try_cast(censor_flag as boolean) as censor_flag,
        cast(target_source as varchar) as target_source,
        try_cast(label_quality_score as double) as label_quality_score,
        coalesce(try_cast(label_quality_missing_flag as boolean), false) as label_quality_missing_flag,
        coalesce(try_cast(label_quality_parse_error_flag as boolean), false) as label_quality_parse_error_flag,
        try_cast(usable_for_training_flag as boolean) as usable_for_training_flag,
        coalesce(try_cast(usable_for_training_missing_flag as boolean), false) as usable_for_training_missing_flag,
        coalesce(try_cast(censor_flag_missing_flag as boolean), false) as censor_flag_missing_flag,
        try_cast(observed_revenue_net as double) as observed_revenue_net,
        try_cast(observed_discount_amount as double) as observed_discount_amount,
        try_cast(promo_flag as boolean) as promo_flag,
        try_cast(holiday_flag as boolean) as holiday_flag,
        try_cast(activity_flag as boolean) as activity_flag,
        try_cast(observed_stockout_flag as boolean) as observed_stockout_flag,
        try_cast(observed_stockout_available as boolean) as observed_stockout_available,
        coalesce(try_cast(observed_stockout_available_missing_flag as boolean), false) as observed_stockout_available_missing_flag,
        try_cast(observed_stockout_intensity as double) as observed_stockout_intensity,
        try_cast(day_complete_flag as boolean) as day_complete_flag,
        cast(calendar_weekday_name as varchar) as calendar_weekday_name,
        try_cast(calendar_day_of_week as integer) as calendar_day_of_week,
        try_cast(calendar_month as integer) as calendar_month,
        try_cast(calendar_year as integer) as calendar_year,
        try_cast(calendar_week_key as integer) as calendar_week_key,
        cast(event_name_1 as varchar) as event_name_1,
        cast(event_type_1 as varchar) as event_type_1,
        cast(event_name_2 as varchar) as event_name_2,
        cast(event_type_2 as varchar) as event_type_2,
        try_cast(weather_precipitation as double) as weather_precipitation,
        try_cast(weather_temperature as double) as weather_temperature,
        try_cast(weather_humidity as double) as weather_humidity,
        try_cast(weather_wind_level as double) as weather_wind_level,
        cast(silver_run_id as varchar) as silver_run_id,
        cast(source_name as varchar) as source_name,
        cast(source_policy_id as varchar) as source_policy_id,
        cast(source_file_path as varchar) as source_file_path,
        try_cast(source_loaded_at as timestamp) as source_loaded_at,
        cast(data_origin as varchar) as data_origin,
        source_priority
    from unioned
),
ranked as (
    select
        *,
        row_number() over (
            partition by dataset_source, dt, location_id, product_id
            order by source_priority, source_loaded_at desc, source_partition, source_run_id, silver_run_id
        ) as source_rank
    from normalized
)
select
    dataset_source,
    source_partition,
    source_run_id,
    series_id,
    dt,
    location_id,
    product_id,
    region_id,
    org_group_id,
    category_level_1,
    category_level_2,
    category_level_3,
    observed_demand_qty,
    observed_demand_missing_flag,
    observed_demand_parse_error_flag,
    target_semantics,
    target_semantics_raw,
    target_semantics_parse_error_flag,
    censor_flag,
    target_source,
    label_quality_score,
    label_quality_missing_flag,
    label_quality_parse_error_flag,
    usable_for_training_flag,
    usable_for_training_missing_flag,
    censor_flag_missing_flag,
    observed_revenue_net,
    observed_discount_amount,
    promo_flag,
    holiday_flag,
    activity_flag,
    observed_stockout_flag,
    observed_stockout_available,
    observed_stockout_available_missing_flag,
    observed_stockout_intensity,
    day_complete_flag,
    calendar_weekday_name,
    calendar_day_of_week,
    calendar_month,
    calendar_year,
    calendar_week_key,
    event_name_1,
    event_type_1,
    event_name_2,
    event_type_2,
    weather_precipitation,
    weather_temperature,
    weather_humidity,
    weather_wind_level,
    silver_run_id,
    source_name,
    source_policy_id,
    source_file_path,
    source_loaded_at,
    data_origin
from ranked
where source_rank = 1
