{{ config(tags=["silver", "bakery"], materialized="table", unique_key=["dataset_source", "dt", "location_id", "product_id"]) }}

select
    dataset_source,
    source_partition,
    source_run_id,
    series_id,
    dt,
    location_id,
    product_id,
    region_id,
    org_group_id,
    category_level_1,
    category_level_2,
    category_level_3,
    sum(observed_demand_qty) as observed_demand_qty,
    'observed_sales' as target_semantics,
    false as censor_flag,
    'observed_sales' as target_source,
    1.0 as label_quality_score,
    true as usable_for_training_flag,
    sum(observed_revenue_net) as observed_revenue_net,
    cast(null as double) as observed_discount_amount,
    cast(null as boolean) as promo_flag,
    cast(null as boolean) as holiday_flag,
    cast(null as boolean) as activity_flag,
    cast(null as boolean) as observed_stockout_flag,
    false as observed_stockout_available,
    cast(null as double) as observed_stockout_intensity,
    cast(null as boolean) as day_complete_flag,
    strftime(dt, '%A') as calendar_weekday_name,
    cast(strftime(dt, '%u') as integer) - 1 as calendar_day_of_week,
    cast(strftime(dt, '%m') as integer) as calendar_month,
    cast(strftime(dt, '%Y') as integer) as calendar_year,
    cast(strftime(dt, '%V') as integer) as calendar_week_key,
    cast(null as varchar) as event_name_1,
    cast(null as varchar) as event_type_1,
    cast(null as varchar) as event_name_2,
    cast(null as varchar) as event_type_2,
    cast(null as double) as weather_precipitation,
    cast(null as double) as weather_temperature,
    cast(null as double) as weather_humidity,
    cast(null as double) as weather_wind_level,
    min(silver_run_id) as silver_run_id
from {{ ref("silver_bakery_order_lines") }}
group by
    dataset_source,
    source_partition,
    source_run_id,
    series_id,
    dt,
    location_id,
    product_id,
    region_id,
    org_group_id,
    category_level_1,
    category_level_2,
    category_level_3
