{{ config(tags=["silver", "bakery"], materialized="table", unique_key=["dataset_source", "source_partition", "row_index"]) }}

select
    coalesce(source_policy_id, 'bakery') as dataset_source,
    source_partition,
    coalesce(source_name, 'bakery') as source_run_id,
    concat('bakery_store_1', '__', product_id) as series_id,
    cast(dt as date) as dt,
    'bakery_store_1' as location_id,
    product_id,
    cast(null as varchar) as region_id,
    cast(null as varchar) as org_group_id,
    cast(null as varchar) as category_level_1,
    cast(null as varchar) as category_level_2,
    cast(null as varchar) as category_level_3,
    try_cast(quantity as double) as observed_demand_qty,
    try_cast(quantity as double) * try_cast(unit_price as double) as observed_revenue_net,
    cast(null as double) as observed_discount_amount,
    cast(null as boolean) as promo_flag,
    cast(null as boolean) as holiday_flag,
    cast(null as boolean) as activity_flag,
    cast(null as boolean) as observed_stockout_flag,
    false as observed_stockout_available,
    cast(null as double) as observed_stockout_intensity,
    cast(null as boolean) as day_complete_flag,
    strftime(dt, '%A') as calendar_weekday_name,
    cast(strftime(dt, '%u') as integer) - 1 as calendar_day_of_week,
    cast(strftime(dt, '%m') as integer) as calendar_month,
    cast(strftime(dt, '%Y') as integer) as calendar_year,
    cast(strftime(dt, '%V') as integer) as calendar_week_key,
    cast(null as varchar) as event_name_1,
    cast(null as varchar) as event_type_1,
    cast(null as varchar) as event_name_2,
    cast(null as varchar) as event_type_2,
    cast(null as double) as weather_precipitation,
    cast(null as double) as weather_temperature,
    cast(null as double) as weather_humidity,
    cast(null as double) as weather_wind_level,
    '{{ env_var("PRAEDIXA_SILVER_RUN_ID", "manual") }}' as silver_run_id,
    cast(source_name as varchar) as source_name,
    cast(coalesce(source_policy_id, 'bakery') as varchar) as source_policy_id,
    cast(source_file_path as varchar) as source_file_path,
    cast(loaded_at as timestamp) as source_loaded_at,
    row_index,
    ticket_number_raw,
    sold_at_local_ts
from {{ ref("stg_bakery_order_lines") }}
