{{ config(tags=["gold", "d1", "training"], materialized="table", schema=env_var('PRAEDIXA_DUCKDB_GOLD_SCHEMA', 'gold')) }}

{% set training_feature_columns = [
    "vertical_level_1",
    "vertical_level_2",
    "commerce_modality",
    "operation_type",
    "service_pattern",
    "country_code",
    "region_code",
    "region_known_flag",
    "city_name",
    "history_available_days",
    "cold_start_bucket",
    "drive_through_flag",
    "delivery_flag",
    "pickup_flag",
    "product_family",
    "product_subfamily",
    "product_subfamily_known_flag",
    "category_level_1",
    "category_level_1_known_flag",
    "category_level_2",
    "category_level_2_known_flag",
    "category_level_3",
    "category_level_3_known_flag",
    "product_taxonomy_depth",
    "target_delta_log_wow_d_plus_1",
    "current_day_demand_qty",
    "is_observed_row",
    "true_zero_demand_flag",
    "day_complete_flag",
    "observed_stockout_flag",
    "observed_stockout_available",
    "observed_discount_amount",
    "promo_flag",
    "activity_flag",
    "target_day_of_week",
    "target_day_of_month",
    "target_week_of_year",
    "target_month",
    "target_quarter",
    "target_year",
    "current_holiday_flag",
    "month_start_flag",
    "month_end_flag",
    "target_weekend_flag",
    "target_holiday_flag",
    "sin_target_day_of_week",
    "cos_target_day_of_week",
    "sin_target_week_of_year",
    "cos_target_week_of_year",
    "sin_target_month",
    "cos_target_month",
    "weather_temperature_lag_0",
    "weather_temperature_lag_1",
    "weather_temperature_lag_2",
    "weather_temperature_lag_3",
    "weather_temperature_lag_4",
    "weather_temperature_lag_5",
    "weather_temperature_lag_6",
    "weather_temperature_lag_7",
    "weather_temperature_lag_14",
    "weather_temperature_rolling_mean_7",
    "weather_temperature_rolling_mean_28",
    "weather_temperature_min_lag_0",
    "weather_temperature_min_lag_1",
    "weather_temperature_min_lag_2",
    "weather_temperature_min_lag_3",
    "weather_temperature_min_lag_4",
    "weather_temperature_min_lag_5",
    "weather_temperature_min_lag_6",
    "weather_temperature_min_lag_7",
    "weather_temperature_min_lag_14",
    "weather_temperature_max_lag_0",
    "weather_temperature_max_lag_1",
    "weather_temperature_max_lag_2",
    "weather_temperature_max_lag_3",
    "weather_temperature_max_lag_4",
    "weather_temperature_max_lag_5",
    "weather_temperature_max_lag_6",
    "weather_temperature_max_lag_7",
    "weather_temperature_max_lag_14",
    "weather_precipitation_lag_0",
    "weather_precipitation_lag_1",
    "weather_precipitation_lag_2",
    "weather_precipitation_lag_3",
    "weather_precipitation_lag_4",
    "weather_precipitation_lag_5",
    "weather_precipitation_lag_6",
    "weather_precipitation_lag_7",
    "weather_precipitation_lag_14",
    "weather_precipitation_rolling_mean_7",
    "weather_precipitation_rolling_mean_28",
    "weather_humidity_lag_0",
    "weather_humidity_lag_1",
    "weather_humidity_lag_2",
    "weather_humidity_lag_3",
    "weather_humidity_lag_4",
    "weather_humidity_lag_5",
    "weather_humidity_lag_6",
    "weather_humidity_lag_7",
    "weather_humidity_lag_14",
    "weather_humidity_rolling_mean_7",
    "weather_wind_level_lag_0",
    "weather_wind_level_lag_1",
    "weather_wind_level_lag_2",
    "weather_wind_level_lag_3",
    "weather_wind_level_lag_4",
    "weather_wind_level_lag_5",
    "weather_wind_level_lag_6",
    "weather_wind_level_lag_7",
    "weather_wind_level_lag_14",
    "weather_wind_level_rolling_mean_7",
    "weather_humidity",
    "weather_wind_level",
    "lending_interest_rate_latest",
    "lending_interest_rate_latest_lag_28",
    "source_legal_basis",
    "source_license_type",
    "source_review_status",
    "source_legal_status_snapshot",
    "source_role",
    "is_synthetic_source",
    "field_baseline_blend_lag_1_lag_7_d_plus_1",
    "lag_1",
    "lag_2",
    "lag_3",
    "lag_4",
    "lag_5",
    "lag_6",
    "lag_7",
    "lag_14",
    "lag_28",
    "target_lag_1",
    "target_lag_2",
    "target_lag_3",
    "target_lag_4",
    "target_lag_5",
    "target_lag_6",
    "target_lag_7",
    "target_lag_14",
    "target_lag_21",
    "target_lag_28",
    "rolling_mean_7",
    "rolling_mean_14",
    "rolling_mean_28",
    "rolling_std_28",
    "observed_revenue_net_lag_1",
    "observed_revenue_net_lag_2",
    "observed_revenue_net_lag_3",
    "observed_revenue_net_lag_4",
    "observed_revenue_net_lag_5",
    "observed_revenue_net_lag_6",
    "observed_revenue_net_lag_7",
    "observed_revenue_net_lag_14",
    "observed_revenue_net_lag_28",
    "observed_discount_amount_lag_1",
    "observed_discount_amount_lag_2",
    "observed_discount_amount_lag_3",
    "observed_discount_amount_lag_4",
    "observed_discount_amount_lag_5",
    "observed_discount_amount_lag_6",
    "observed_discount_amount_lag_7",
    "observed_discount_amount_lag_14",
    "observed_discount_amount_lag_28",
    "observed_discount_amount_rolling_mean_7",
    "observed_discount_amount_rolling_mean_28",
    "promo_flag_lag_1",
    "promo_flag_lag_2",
    "promo_flag_lag_3",
    "promo_flag_lag_4",
    "promo_flag_lag_5",
    "promo_flag_lag_6",
    "promo_flag_lag_7",
    "promo_flag_lag_14",
    "promo_flag_lag_28",
    "promo_rate_7",
    "promo_rate_28",
    "activity_flag_lag_1",
    "activity_flag_lag_2",
    "activity_flag_lag_3",
    "activity_flag_lag_4",
    "activity_flag_lag_5",
    "activity_flag_lag_6",
    "activity_flag_lag_7",
    "activity_flag_lag_14",
    "activity_flag_lag_28",
    "activity_rate_7",
    "activity_rate_28",
    "observed_stockout_flag_lag_1",
    "observed_stockout_flag_lag_2",
    "observed_stockout_flag_lag_3",
    "observed_stockout_flag_lag_4",
    "observed_stockout_flag_lag_5",
    "observed_stockout_flag_lag_6",
    "observed_stockout_flag_lag_7",
    "observed_stockout_flag_lag_14",
    "observed_stockout_flag_lag_28",
    "observed_stockout_rate_7",
    "observed_stockout_rate_28",
    "censor_flag_lag_1",
    "censor_flag_lag_2",
    "censor_flag_lag_3",
    "censor_flag_lag_4",
    "censor_flag_lag_5",
    "censor_flag_lag_6",
    "censor_flag_lag_7",
    "censor_flag_lag_14",
    "censor_flag_lag_28",
    "censor_rate_7",
    "censor_rate_28",
    "label_quality_score_lag_1",
    "label_quality_score_lag_2",
    "label_quality_score_lag_3",
    "label_quality_score_lag_4",
    "label_quality_score_lag_5",
    "label_quality_score_lag_6",
    "label_quality_score_lag_7",
    "label_quality_score_lag_14",
    "label_quality_score_lag_28",
    "label_quality_score_rolling_mean_7",
    "label_quality_score_rolling_mean_28",
    "day_complete_flag_lag_1",
    "day_complete_flag_lag_2",
    "day_complete_flag_lag_3",
    "day_complete_flag_lag_4",
    "day_complete_flag_lag_5",
    "day_complete_flag_lag_6",
    "day_complete_flag_lag_7",
    "day_complete_flag_lag_14",
    "day_complete_flag_lag_28",
    "day_complete_rate_7",
    "day_complete_rate_28",
    "same_dow_mean_4w",
    "target_same_dow_mean_4w",
    "naive_last_value",
    "seasonal_naive_d7",
    "target_seasonal_naive_d7",
    "moving_average_7",
    "moving_average_28",
    "data_quality_metadata_unavailable_count",
    "data_quality_metadata_missing_count",
    "data_quality_pricing_promo_unavailable_count",
    "data_quality_pricing_promo_missing_count",
    "data_quality_weather_unavailable_count",
    "data_quality_weather_missing_count",
    "data_quality_macro_unavailable_count",
    "data_quality_macro_missing_count",
    "data_quality_operations_unavailable_count",
    "data_quality_operations_missing_count",
    "data_quality_history_unavailable_count",
    "data_quality_history_missing_count",
    "sample_weight_source",
    "sample_weight_business",
    "is_primary_eval_dataset",
    "gold_run_id",
] %}

select
    cast(dataset_source as varchar) as dataset_source,
    cast(dataset_source as varchar) as dataset_source_static_cat,
    cast(source_partition as varchar) as source_partition,
    cast(source_run_id as varchar) as source_run_id,
    cast(client_id as varchar) as client_id,
    cast(dt as date) as dt,
    cast(target_dt as date) as target_dt,
    1 as forecast_horizon_days,
    cast(decision_timestamp as timestamp) as decision_timestamp,
    cast(feature_availability_profile as varchar) as feature_availability_profile,
    cast(split_bucket as varchar) as split_bucket,
    cast(location_id as varchar) as location_id,
    cast(product_id as varchar) as product_id,
    try_cast(target_demand_qty_d_plus_1 as double) as target_demand_qty_d_plus_1,
    try_cast(target_residual_field_blend_lag_1_lag_7_d_plus_1 as double) as target_residual_field_blend_lag_1_lag_7_d_plus_1,
    cast(target_semantics as varchar) as target_semantics,
    coalesce(try_cast(censor_flag as boolean), false) as censor_flag,
    cast(target_source as varchar) as target_source,
    try_cast(label_quality_score as double) as label_quality_score,
    coalesce(try_cast(usable_for_training_flag as boolean), false) as usable_for_training_flag,
    coalesce(try_cast(target_true_zero_demand_flag as boolean), false) as target_true_zero_demand_flag,
{% for column in training_feature_columns %}
    {%- set role_suffix = praedixa_feature_role_suffix(column) -%}
    {{ column }}{{ "," if role_suffix or not loop.last }}
    {%- if role_suffix %}
    {{ column }} as {{ column }}{{ role_suffix }}{{ "," if not loop.last }}
    {%- endif %}
{% endfor %}
from {{ ref('gold_daily_product_forecast_panel_d1') }}
