{{ config(tags=["gold", "d1"], materialized="view", schema=env_var("PRAEDIXA_DUCKDB_GOLD_SCHEMA", "gold")) }}

{% set data_quality_metadata_bases = [
    "country_code",
    "region_code",
    "city_name",
    "product_subfamily",
    "category_level_1",
    "category_level_2",
    "category_level_3",
] %}
{% set data_quality_pricing_promo_bases = [
    "avg_selling_price",
    "observed_discount_amount",
    "promo_flag",
    "activity_flag",
    "avg_selling_price_lag_1",
    "avg_selling_price_lag_7",
    "avg_selling_price_lag_28",
    "observed_discount_amount_lag_1",
    "observed_discount_amount_lag_7",
    "observed_discount_amount_lag_28",
    "observed_discount_amount_rolling_mean_7",
    "observed_discount_amount_rolling_mean_28",
    "promo_flag_lag_1",
    "promo_flag_lag_7",
    "promo_flag_lag_28",
    "promo_rate_7",
    "promo_rate_28",
    "activity_flag_lag_1",
    "activity_flag_lag_7",
    "activity_flag_lag_28",
    "activity_rate_7",
    "activity_rate_28",
] %}
{% set data_quality_weather_bases = [
    "weather_temperature_lag_0",
    "weather_temperature_lag_1",
    "weather_temperature_lag_7",
    "weather_temperature_rolling_mean_7",
    "weather_temperature_rolling_mean_28",
    "weather_temperature_min_lag_0",
    "weather_temperature_min_lag_1",
    "weather_temperature_min_lag_7",
    "weather_temperature_max_lag_0",
    "weather_temperature_max_lag_1",
    "weather_temperature_max_lag_7",
    "weather_precipitation_lag_0",
    "weather_precipitation_lag_1",
    "weather_precipitation_lag_7",
    "weather_precipitation_rolling_mean_7",
    "weather_precipitation_rolling_mean_28",
    "weather_humidity_lag_0",
    "weather_humidity_lag_1",
    "weather_humidity_lag_7",
    "weather_humidity_rolling_mean_7",
    "weather_wind_level_lag_0",
    "weather_wind_level_lag_1",
    "weather_wind_level_lag_7",
    "weather_wind_level_rolling_mean_7",
    "weather_humidity",
    "weather_wind_level",
] %}
{% set data_quality_macro_bases = [
    "lending_interest_rate_latest",
    "lending_interest_rate_latest_lag_28",
] %}
{% set data_quality_operations_bases = [
    "target_delta_log_wow_d_plus_1",
    "current_day_demand_qty",
    "observed_stockout_flag",
] %}
{% set data_quality_history_bases = [
    "lag_1",
    "lag_7",
    "lag_14",
    "lag_28",
    "target_lag_7",
    "target_lag_14",
    "target_lag_21",
    "target_lag_28",
    "rolling_mean_7",
    "rolling_mean_14",
    "rolling_mean_28",
    "rolling_std_28",
    "observed_stockout_flag_lag_1",
    "observed_stockout_flag_lag_7",
    "observed_stockout_flag_lag_28",
    "observed_stockout_rate_7",
    "observed_stockout_rate_28",
    "same_dow_mean_4w",
    "target_same_dow_mean_4w",
    "naive_last_value",
    "seasonal_naive_d7",
    "target_seasonal_naive_d7",
    "moving_average_7",
    "moving_average_28",
] %}
{% set data_quality_families = [
    ("metadata", data_quality_metadata_bases),
    ("pricing_promo", data_quality_pricing_promo_bases),
    ("weather", data_quality_weather_bases),
    ("macro", data_quality_macro_bases),
    ("operations", data_quality_operations_bases),
    ("history", data_quality_history_bases),
] %}
{% set feature_status_bases = (
    data_quality_metadata_bases
    + data_quality_pricing_promo_bases
    + data_quality_weather_bases
    + data_quality_macro_bases
    + data_quality_operations_bases
    + data_quality_history_bases
) %}

with raw_features as (
    select *
    from {{ ref("gold_feature_panel_d1") }}
),
features as (
    select
        raw_features.* exclude (
            holiday_flag,
            school_holiday_flag,
            bridge_day_flag,
            pre_holiday_flag,
            post_holiday_flag
        ),
        raw_features.holiday_flag as current_holiday_flag,
        raw_features.school_holiday_flag as current_school_holiday_flag
    from raw_features
),
source_weights as (
    select *
    from {{ ref("gold_source_weights_d1") }}
),
dataset_applicability as (
    select
        dataset_source,
        max(case when country_code is not null then 1 else 0 end) as country_code_applicable_flag,
        max(case when region_code is not null then 1 else 0 end) as region_code_applicable_flag,
        max(case when city_name is not null then 1 else 0 end) as city_name_applicable_flag,
        max(case when product_subfamily is not null then 1 else 0 end) as product_subfamily_applicable_flag,
        max(case when category_level_1 is not null then 1 else 0 end) as category_level_1_applicable_flag,
        max(case when category_level_2 is not null then 1 else 0 end) as category_level_2_applicable_flag,
        max(case when category_level_3 is not null then 1 else 0 end) as category_level_3_applicable_flag,
        max(case when target_delta_log_wow_d_plus_1 is not null then 1 else 0 end) as target_delta_log_wow_d_plus_1_applicable_flag,
        max(case when current_day_demand_qty is not null then 1 else 0 end) as current_day_demand_qty_applicable_flag,
        max(case when observed_stockout_flag is not null then 1 else 0 end) as observed_stockout_flag_applicable_flag,
        max(case when avg_selling_price is not null then 1 else 0 end) as avg_selling_price_applicable_flag,
        max(case when observed_discount_amount is not null then 1 else 0 end) as observed_discount_amount_applicable_flag,
        max(case when promo_flag is not null then 1 else 0 end) as promo_flag_applicable_flag,
        max(case when activity_flag is not null then 1 else 0 end) as activity_flag_applicable_flag,
        max(case when weather_temperature_lag_0 is not null then 1 else 0 end) as weather_temperature_lag_0_applicable_flag,
        max(case when weather_temperature_lag_1 is not null then 1 else 0 end) as weather_temperature_lag_1_applicable_flag,
        max(case when weather_temperature_lag_7 is not null then 1 else 0 end) as weather_temperature_lag_7_applicable_flag,
        max(case when weather_temperature_rolling_mean_7 is not null then 1 else 0 end) as weather_temperature_rolling_mean_7_applicable_flag,
        max(case when weather_temperature_rolling_mean_28 is not null then 1 else 0 end) as weather_temperature_rolling_mean_28_applicable_flag,
        max(case when weather_temperature_min_lag_0 is not null then 1 else 0 end) as weather_temperature_min_lag_0_applicable_flag,
        max(case when weather_temperature_min_lag_1 is not null then 1 else 0 end) as weather_temperature_min_lag_1_applicable_flag,
        max(case when weather_temperature_min_lag_7 is not null then 1 else 0 end) as weather_temperature_min_lag_7_applicable_flag,
        max(case when weather_temperature_max_lag_0 is not null then 1 else 0 end) as weather_temperature_max_lag_0_applicable_flag,
        max(case when weather_temperature_max_lag_1 is not null then 1 else 0 end) as weather_temperature_max_lag_1_applicable_flag,
        max(case when weather_temperature_max_lag_7 is not null then 1 else 0 end) as weather_temperature_max_lag_7_applicable_flag,
        max(case when weather_precipitation_lag_0 is not null then 1 else 0 end) as weather_precipitation_lag_0_applicable_flag,
        max(case when weather_precipitation_lag_1 is not null then 1 else 0 end) as weather_precipitation_lag_1_applicable_flag,
        max(case when weather_precipitation_lag_7 is not null then 1 else 0 end) as weather_precipitation_lag_7_applicable_flag,
        max(case when weather_precipitation_rolling_mean_7 is not null then 1 else 0 end) as weather_precipitation_rolling_mean_7_applicable_flag,
        max(case when weather_precipitation_rolling_mean_28 is not null then 1 else 0 end) as weather_precipitation_rolling_mean_28_applicable_flag,
        max(case when weather_humidity_lag_0 is not null then 1 else 0 end) as weather_humidity_lag_0_applicable_flag,
        max(case when weather_humidity_lag_1 is not null then 1 else 0 end) as weather_humidity_lag_1_applicable_flag,
        max(case when weather_humidity_lag_7 is not null then 1 else 0 end) as weather_humidity_lag_7_applicable_flag,
        max(case when weather_humidity_rolling_mean_7 is not null then 1 else 0 end) as weather_humidity_rolling_mean_7_applicable_flag,
        max(case when weather_wind_level_lag_0 is not null then 1 else 0 end) as weather_wind_level_lag_0_applicable_flag,
        max(case when weather_wind_level_lag_1 is not null then 1 else 0 end) as weather_wind_level_lag_1_applicable_flag,
        max(case when weather_wind_level_lag_7 is not null then 1 else 0 end) as weather_wind_level_lag_7_applicable_flag,
        max(case when weather_wind_level_rolling_mean_7 is not null then 1 else 0 end) as weather_wind_level_rolling_mean_7_applicable_flag,
        max(case when weather_humidity is not null then 1 else 0 end) as weather_humidity_applicable_flag,
        max(case when weather_wind_level is not null then 1 else 0 end) as weather_wind_level_applicable_flag,
        max(case when lending_interest_rate_latest is not null then 1 else 0 end) as lending_interest_rate_latest_applicable_flag,
        max(case when lending_interest_rate_latest_lag_28 is not null then 1 else 0 end) as lending_interest_rate_latest_lag_28_applicable_flag,
        max(case when lag_1 is not null then 1 else 0 end) as lag_1_applicable_flag,
        max(case when lag_7 is not null then 1 else 0 end) as lag_7_applicable_flag,
        max(case when lag_14 is not null then 1 else 0 end) as lag_14_applicable_flag,
        max(case when lag_28 is not null then 1 else 0 end) as lag_28_applicable_flag,
        max(case when target_lag_7 is not null then 1 else 0 end) as target_lag_7_applicable_flag,
        max(case when target_lag_14 is not null then 1 else 0 end) as target_lag_14_applicable_flag,
        max(case when target_lag_21 is not null then 1 else 0 end) as target_lag_21_applicable_flag,
        max(case when target_lag_28 is not null then 1 else 0 end) as target_lag_28_applicable_flag,
        max(case when rolling_mean_7 is not null then 1 else 0 end) as rolling_mean_7_applicable_flag,
        max(case when rolling_mean_14 is not null then 1 else 0 end) as rolling_mean_14_applicable_flag,
        max(case when rolling_mean_28 is not null then 1 else 0 end) as rolling_mean_28_applicable_flag,
        max(case when rolling_std_28 is not null then 1 else 0 end) as rolling_std_28_applicable_flag,
        max(case when avg_selling_price_lag_1 is not null then 1 else 0 end) as avg_selling_price_lag_1_applicable_flag,
        max(case when avg_selling_price_lag_7 is not null then 1 else 0 end) as avg_selling_price_lag_7_applicable_flag,
        max(case when avg_selling_price_lag_28 is not null then 1 else 0 end) as avg_selling_price_lag_28_applicable_flag,
        max(case when observed_discount_amount_lag_1 is not null then 1 else 0 end) as observed_discount_amount_lag_1_applicable_flag,
        max(case when observed_discount_amount_lag_7 is not null then 1 else 0 end) as observed_discount_amount_lag_7_applicable_flag,
        max(case when observed_discount_amount_lag_28 is not null then 1 else 0 end) as observed_discount_amount_lag_28_applicable_flag,
        max(case when observed_discount_amount_rolling_mean_7 is not null then 1 else 0 end) as observed_discount_amount_rolling_mean_7_applicable_flag,
        max(case when observed_discount_amount_rolling_mean_28 is not null then 1 else 0 end) as observed_discount_amount_rolling_mean_28_applicable_flag,
        max(case when promo_flag_lag_1 is not null then 1 else 0 end) as promo_flag_lag_1_applicable_flag,
        max(case when promo_flag_lag_7 is not null then 1 else 0 end) as promo_flag_lag_7_applicable_flag,
        max(case when promo_flag_lag_28 is not null then 1 else 0 end) as promo_flag_lag_28_applicable_flag,
        max(case when promo_rate_7 is not null then 1 else 0 end) as promo_rate_7_applicable_flag,
        max(case when promo_rate_28 is not null then 1 else 0 end) as promo_rate_28_applicable_flag,
        max(case when activity_flag_lag_1 is not null then 1 else 0 end) as activity_flag_lag_1_applicable_flag,
        max(case when activity_flag_lag_7 is not null then 1 else 0 end) as activity_flag_lag_7_applicable_flag,
        max(case when activity_flag_lag_28 is not null then 1 else 0 end) as activity_flag_lag_28_applicable_flag,
        max(case when activity_rate_7 is not null then 1 else 0 end) as activity_rate_7_applicable_flag,
        max(case when activity_rate_28 is not null then 1 else 0 end) as activity_rate_28_applicable_flag,
        max(case when observed_stockout_flag_lag_1 is not null then 1 else 0 end) as observed_stockout_flag_lag_1_applicable_flag,
        max(case when observed_stockout_flag_lag_7 is not null then 1 else 0 end) as observed_stockout_flag_lag_7_applicable_flag,
        max(case when observed_stockout_flag_lag_28 is not null then 1 else 0 end) as observed_stockout_flag_lag_28_applicable_flag,
        max(case when observed_stockout_rate_7 is not null then 1 else 0 end) as observed_stockout_rate_7_applicable_flag,
        max(case when observed_stockout_rate_28 is not null then 1 else 0 end) as observed_stockout_rate_28_applicable_flag,
        max(case when same_dow_mean_4w is not null then 1 else 0 end) as same_dow_mean_4w_applicable_flag,
        max(case when target_same_dow_mean_4w is not null then 1 else 0 end) as target_same_dow_mean_4w_applicable_flag,
        max(case when naive_last_value is not null then 1 else 0 end) as naive_last_value_applicable_flag,
        max(case when seasonal_naive_d7 is not null then 1 else 0 end) as seasonal_naive_d7_applicable_flag,
        max(case when target_seasonal_naive_d7 is not null then 1 else 0 end) as target_seasonal_naive_d7_applicable_flag,
        max(case when moving_average_7 is not null then 1 else 0 end) as moving_average_7_applicable_flag,
        max(case when moving_average_28 is not null then 1 else 0 end) as moving_average_28_applicable_flag
    from features
    group by dataset_source
),
weighted as (
    select
        features.*,
        dataset_applicability.* exclude (dataset_source),
        source_weights.sample_weight_source,
        1.0 as sample_weight_business,
        features.dataset_source = 'bakery' as is_primary_eval_dataset
    from features
    inner join dataset_applicability
      on features.dataset_source = dataset_applicability.dataset_source
    inner join source_weights
      on features.split_bucket = source_weights.split_bucket
     and features.dataset_source = source_weights.dataset_source
),
legacy_panel as (
select
    weighted.dataset_source,
    weighted.client_id,
    weighted.vertical_level_1,
    weighted.vertical_level_2,
    weighted.country_code_applicable_flag as country_code_applicable_flag,

    coalesce(weighted.country_code, '0') as country_code,
    case when weighted.country_code_applicable_flag = 1 and weighted.country_code is null then 1 else 0 end as country_code_missing_flag,
    weighted.region_code_applicable_flag as region_code_applicable_flag,
    coalesce(weighted.region_code, '0') as region_code,
    case when weighted.region_code_applicable_flag = 1 and weighted.region_code is null then 1 else 0 end as region_code_missing_flag,
    weighted.city_name_applicable_flag as city_name_applicable_flag,
    coalesce(weighted.city_name, '0') as city_name,
    case when weighted.city_name_applicable_flag = 1 and weighted.city_name is null then 1 else 0 end as city_name_missing_flag,
    weighted.history_available_days,
    weighted.cold_start_bucket,
    weighted.site_format,
    weighted.service_model,
    weighted.drive_through_flag,
    weighted.delivery_flag,
    weighted.pickup_flag,
    weighted.late_night_flag,
    weighted.trade_area_type,
    weighted.office_density_bucket,
    weighted.residential_density_bucket,
    weighted.competition_intensity_bucket,
    weighted.product_family,
    weighted.product_subfamily_applicable_flag as product_subfamily_applicable_flag,

    coalesce(weighted.product_subfamily, '0') as product_subfamily,
    case when weighted.product_subfamily_applicable_flag = 1 and weighted.product_subfamily is null then 1 else 0 end as product_subfamily_missing_flag,
    weighted.menu_role,
    weighted.price_band,
    weighted.series_id,
    weighted.location_id,
    weighted.product_id,
    weighted.category_level_1_applicable_flag as category_level_1_applicable_flag,

    coalesce(weighted.category_level_1, '0') as category_level_1,
    case when weighted.category_level_1_applicable_flag = 1 and weighted.category_level_1 is null then 1 else 0 end as category_level_1_missing_flag,
    weighted.category_level_2_applicable_flag as category_level_2_applicable_flag,
    coalesce(weighted.category_level_2, '0') as category_level_2,
    case when weighted.category_level_2_applicable_flag = 1 and weighted.category_level_2 is null then 1 else 0 end as category_level_2_missing_flag,
    weighted.category_level_3_applicable_flag as category_level_3_applicable_flag,
    coalesce(weighted.category_level_3, '0') as category_level_3,
    case when weighted.category_level_3_applicable_flag = 1 and weighted.category_level_3 is null then 1 else 0 end as category_level_3_missing_flag,
    weighted.dt,
    weighted.target_dt,
    weighted.split_bucket,
    weighted.target_demand_qty_d_plus_1,
    weighted.target_delta_log_wow_d_plus_1_applicable_flag as target_delta_log_wow_d_plus_1_applicable_flag,

    coalesce(weighted.target_delta_log_wow_d_plus_1, 0) as target_delta_log_wow_d_plus_1,
    case when weighted.target_delta_log_wow_d_plus_1_applicable_flag = 1 and weighted.target_delta_log_wow_d_plus_1 is null then 1 else 0 end as target_delta_log_wow_d_plus_1_missing_flag,
    weighted.current_day_demand_qty_applicable_flag as current_day_demand_qty_applicable_flag,
    coalesce(weighted.current_day_demand_qty, 0) as current_day_demand_qty,
    case when weighted.current_day_demand_qty_applicable_flag = 1 and weighted.current_day_demand_qty is null then 1 else 0 end as current_day_demand_qty_missing_flag,
    weighted.is_observed_row,
    weighted.true_zero_demand_flag,
    weighted.location_closed_flag,
    weighted.location_open_flag,
    weighted.product_active_flag,
    weighted.day_complete_flag,
    weighted.missing_sales_flag,
    weighted.observed_stockout_flag_applicable_flag as observed_stockout_flag_applicable_flag,

    coalesce(weighted.observed_stockout_flag, false) as observed_stockout_flag,
    case when weighted.observed_stockout_flag_applicable_flag = 1 and weighted.observed_stockout_flag is null then 1 else 0 end as observed_stockout_flag_missing_flag,
    weighted.observed_stockout_available,
    weighted.anomaly_flag,
    weighted.freshretail_rescaled_flag,
    weighted.target_scale_assumption,
    weighted.avg_selling_price_applicable_flag as avg_selling_price_applicable_flag,

    coalesce(weighted.avg_selling_price, 0) as avg_selling_price,
    case when weighted.avg_selling_price_applicable_flag = 1 and weighted.avg_selling_price is null then 1 else 0 end as avg_selling_price_missing_flag,
    weighted.observed_discount_amount_applicable_flag as observed_discount_amount_applicable_flag,
    coalesce(weighted.observed_discount_amount, 0) as observed_discount_amount,
    case when weighted.observed_discount_amount_applicable_flag = 1 and weighted.observed_discount_amount is null then 1 else 0 end as observed_discount_amount_missing_flag,
    weighted.promo_flag_applicable_flag as promo_flag_applicable_flag,
    coalesce(weighted.promo_flag, false) as promo_flag,
    case when weighted.promo_flag_applicable_flag = 1 and weighted.promo_flag is null then 1 else 0 end as promo_flag_missing_flag,
    weighted.price_available,
    weighted.activity_flag_applicable_flag as activity_flag_applicable_flag,

    coalesce(weighted.activity_flag, false) as activity_flag,
    case when weighted.activity_flag_applicable_flag = 1 and weighted.activity_flag is null then 1 else 0 end as activity_flag_missing_flag,
    weighted.target_day_of_week,
    weighted.target_day_of_month,
    weighted.target_week_of_year,
    weighted.target_month,
    weighted.target_quarter,
    weighted.target_year,
    weighted.current_holiday_flag,
    weighted.current_holiday_name,
    weighted.current_school_holiday_flag,
    weighted.current_school_holiday_name,
    weighted.holiday_name_local as current_holiday_name_local,
    weighted.school_holiday_flag_local,
    case
        when weighted.school_holiday_flag_local then coalesce(weighted.school_holiday_name_local, 'school_holiday_unspecified')
        else 'no_school_holiday'
    end as current_school_holiday_name_local,
    weighted.payday_flag,
    weighted.month_start_flag,
    weighted.month_end_flag,
    weighted.target_weekend_flag,
    weighted.target_holiday_flag,
    weighted.target_holiday_name,
    weighted.target_school_holiday_flag,
    weighted.target_school_holiday_name,
    weighted.sin_target_day_of_week,
    weighted.cos_target_day_of_week,
    weighted.sin_target_week_of_year,
    weighted.cos_target_week_of_year,
    weighted.sin_target_month,
    weighted.cos_target_month,
    weighted.weather_temperature_lag_0_applicable_flag as weather_temperature_lag_0_applicable_flag,

    coalesce(weighted.weather_temperature_lag_0, 0) as weather_temperature_lag_0,
    case when weighted.weather_temperature_lag_0_applicable_flag = 1 and weighted.weather_temperature_lag_0 is null then 1 else 0 end as weather_temperature_lag_0_missing_flag,
    weighted.weather_temperature_lag_1_applicable_flag as weather_temperature_lag_1_applicable_flag,
    coalesce(weighted.weather_temperature_lag_1, 0) as weather_temperature_lag_1,
    case when weighted.weather_temperature_lag_1_applicable_flag = 1 and weighted.weather_temperature_lag_1 is null then 1 else 0 end as weather_temperature_lag_1_missing_flag,
    weighted.weather_temperature_lag_7_applicable_flag as weather_temperature_lag_7_applicable_flag,
    coalesce(weighted.weather_temperature_lag_7, 0) as weather_temperature_lag_7,
    case when weighted.weather_temperature_lag_7_applicable_flag = 1 and weighted.weather_temperature_lag_7 is null then 1 else 0 end as weather_temperature_lag_7_missing_flag,
    weighted.weather_temperature_rolling_mean_7_applicable_flag as weather_temperature_rolling_mean_7_applicable_flag,
    coalesce(weighted.weather_temperature_rolling_mean_7, 0) as weather_temperature_rolling_mean_7,
    case when weighted.weather_temperature_rolling_mean_7_applicable_flag = 1 and weighted.weather_temperature_rolling_mean_7 is null then 1 else 0 end as weather_temperature_rolling_mean_7_missing_flag,
    weighted.weather_temperature_rolling_mean_28_applicable_flag as weather_temperature_rolling_mean_28_applicable_flag,
    coalesce(weighted.weather_temperature_rolling_mean_28, 0) as weather_temperature_rolling_mean_28,
    case when weighted.weather_temperature_rolling_mean_28_applicable_flag = 1 and weighted.weather_temperature_rolling_mean_28 is null then 1 else 0 end as weather_temperature_rolling_mean_28_missing_flag,
    weighted.weather_temperature_min_lag_0_applicable_flag as weather_temperature_min_lag_0_applicable_flag,
    coalesce(weighted.weather_temperature_min_lag_0, 0) as weather_temperature_min_lag_0,
    case when weighted.weather_temperature_min_lag_0_applicable_flag = 1 and weighted.weather_temperature_min_lag_0 is null then 1 else 0 end as weather_temperature_min_lag_0_missing_flag,
    weighted.weather_temperature_min_lag_1_applicable_flag as weather_temperature_min_lag_1_applicable_flag,
    coalesce(weighted.weather_temperature_min_lag_1, 0) as weather_temperature_min_lag_1,
    case when weighted.weather_temperature_min_lag_1_applicable_flag = 1 and weighted.weather_temperature_min_lag_1 is null then 1 else 0 end as weather_temperature_min_lag_1_missing_flag,
    weighted.weather_temperature_min_lag_7_applicable_flag as weather_temperature_min_lag_7_applicable_flag,
    coalesce(weighted.weather_temperature_min_lag_7, 0) as weather_temperature_min_lag_7,
    case when weighted.weather_temperature_min_lag_7_applicable_flag = 1 and weighted.weather_temperature_min_lag_7 is null then 1 else 0 end as weather_temperature_min_lag_7_missing_flag,
    weighted.weather_temperature_max_lag_0_applicable_flag as weather_temperature_max_lag_0_applicable_flag,
    coalesce(weighted.weather_temperature_max_lag_0, 0) as weather_temperature_max_lag_0,
    case when weighted.weather_temperature_max_lag_0_applicable_flag = 1 and weighted.weather_temperature_max_lag_0 is null then 1 else 0 end as weather_temperature_max_lag_0_missing_flag,
    weighted.weather_temperature_max_lag_1_applicable_flag as weather_temperature_max_lag_1_applicable_flag,
    coalesce(weighted.weather_temperature_max_lag_1, 0) as weather_temperature_max_lag_1,
    case when weighted.weather_temperature_max_lag_1_applicable_flag = 1 and weighted.weather_temperature_max_lag_1 is null then 1 else 0 end as weather_temperature_max_lag_1_missing_flag,
    weighted.weather_temperature_max_lag_7_applicable_flag as weather_temperature_max_lag_7_applicable_flag,
    coalesce(weighted.weather_temperature_max_lag_7, 0) as weather_temperature_max_lag_7,
    case when weighted.weather_temperature_max_lag_7_applicable_flag = 1 and weighted.weather_temperature_max_lag_7 is null then 1 else 0 end as weather_temperature_max_lag_7_missing_flag,
    weighted.weather_precipitation_lag_0_applicable_flag as weather_precipitation_lag_0_applicable_flag,
    coalesce(weighted.weather_precipitation_lag_0, 0) as weather_precipitation_lag_0,
    case when weighted.weather_precipitation_lag_0_applicable_flag = 1 and weighted.weather_precipitation_lag_0 is null then 1 else 0 end as weather_precipitation_lag_0_missing_flag,
    weighted.weather_precipitation_lag_1_applicable_flag as weather_precipitation_lag_1_applicable_flag,
    coalesce(weighted.weather_precipitation_lag_1, 0) as weather_precipitation_lag_1,
    case when weighted.weather_precipitation_lag_1_applicable_flag = 1 and weighted.weather_precipitation_lag_1 is null then 1 else 0 end as weather_precipitation_lag_1_missing_flag,
    weighted.weather_precipitation_lag_7_applicable_flag as weather_precipitation_lag_7_applicable_flag,
    coalesce(weighted.weather_precipitation_lag_7, 0) as weather_precipitation_lag_7,
    case when weighted.weather_precipitation_lag_7_applicable_flag = 1 and weighted.weather_precipitation_lag_7 is null then 1 else 0 end as weather_precipitation_lag_7_missing_flag,
    weighted.weather_precipitation_rolling_mean_7_applicable_flag as weather_precipitation_rolling_mean_7_applicable_flag,
    coalesce(weighted.weather_precipitation_rolling_mean_7, 0) as weather_precipitation_rolling_mean_7,
    case when weighted.weather_precipitation_rolling_mean_7_applicable_flag = 1 and weighted.weather_precipitation_rolling_mean_7 is null then 1 else 0 end as weather_precipitation_rolling_mean_7_missing_flag,
    weighted.weather_precipitation_rolling_mean_28_applicable_flag as weather_precipitation_rolling_mean_28_applicable_flag,
    coalesce(weighted.weather_precipitation_rolling_mean_28, 0) as weather_precipitation_rolling_mean_28,
    case when weighted.weather_precipitation_rolling_mean_28_applicable_flag = 1 and weighted.weather_precipitation_rolling_mean_28 is null then 1 else 0 end as weather_precipitation_rolling_mean_28_missing_flag,
    weighted.weather_humidity_lag_0_applicable_flag as weather_humidity_lag_0_applicable_flag,
    coalesce(weighted.weather_humidity_lag_0, 0) as weather_humidity_lag_0,
    case when weighted.weather_humidity_lag_0_applicable_flag = 1 and weighted.weather_humidity_lag_0 is null then 1 else 0 end as weather_humidity_lag_0_missing_flag,
    weighted.weather_humidity_lag_1_applicable_flag as weather_humidity_lag_1_applicable_flag,
    coalesce(weighted.weather_humidity_lag_1, 0) as weather_humidity_lag_1,
    case when weighted.weather_humidity_lag_1_applicable_flag = 1 and weighted.weather_humidity_lag_1 is null then 1 else 0 end as weather_humidity_lag_1_missing_flag,
    weighted.weather_humidity_lag_7_applicable_flag as weather_humidity_lag_7_applicable_flag,
    coalesce(weighted.weather_humidity_lag_7, 0) as weather_humidity_lag_7,
    case when weighted.weather_humidity_lag_7_applicable_flag = 1 and weighted.weather_humidity_lag_7 is null then 1 else 0 end as weather_humidity_lag_7_missing_flag,
    weighted.weather_humidity_rolling_mean_7_applicable_flag as weather_humidity_rolling_mean_7_applicable_flag,
    coalesce(weighted.weather_humidity_rolling_mean_7, 0) as weather_humidity_rolling_mean_7,
    case when weighted.weather_humidity_rolling_mean_7_applicable_flag = 1 and weighted.weather_humidity_rolling_mean_7 is null then 1 else 0 end as weather_humidity_rolling_mean_7_missing_flag,
    weighted.weather_wind_level_lag_0_applicable_flag as weather_wind_level_lag_0_applicable_flag,
    coalesce(weighted.weather_wind_level_lag_0, 0) as weather_wind_level_lag_0,
    case when weighted.weather_wind_level_lag_0_applicable_flag = 1 and weighted.weather_wind_level_lag_0 is null then 1 else 0 end as weather_wind_level_lag_0_missing_flag,
    weighted.weather_wind_level_lag_1_applicable_flag as weather_wind_level_lag_1_applicable_flag,
    coalesce(weighted.weather_wind_level_lag_1, 0) as weather_wind_level_lag_1,
    case when weighted.weather_wind_level_lag_1_applicable_flag = 1 and weighted.weather_wind_level_lag_1 is null then 1 else 0 end as weather_wind_level_lag_1_missing_flag,
    weighted.weather_wind_level_lag_7_applicable_flag as weather_wind_level_lag_7_applicable_flag,
    coalesce(weighted.weather_wind_level_lag_7, 0) as weather_wind_level_lag_7,
    case when weighted.weather_wind_level_lag_7_applicable_flag = 1 and weighted.weather_wind_level_lag_7 is null then 1 else 0 end as weather_wind_level_lag_7_missing_flag,
    weighted.weather_wind_level_rolling_mean_7_applicable_flag as weather_wind_level_rolling_mean_7_applicable_flag,
    coalesce(weighted.weather_wind_level_rolling_mean_7, 0) as weather_wind_level_rolling_mean_7,
    case when weighted.weather_wind_level_rolling_mean_7_applicable_flag = 1 and weighted.weather_wind_level_rolling_mean_7 is null then 1 else 0 end as weather_wind_level_rolling_mean_7_missing_flag,
    weighted.weather_humidity_applicable_flag as weather_humidity_applicable_flag,
    coalesce(weighted.weather_humidity, 0) as weather_humidity,
    case when weighted.weather_humidity_applicable_flag = 1 and weighted.weather_humidity is null then 1 else 0 end as weather_humidity_missing_flag,
    weighted.weather_wind_level_applicable_flag as weather_wind_level_applicable_flag,
    coalesce(weighted.weather_wind_level, 0) as weather_wind_level,
    case when weighted.weather_wind_level_applicable_flag = 1 and weighted.weather_wind_level is null then 1 else 0 end as weather_wind_level_missing_flag,
    weighted.lending_interest_rate_latest_applicable_flag as lending_interest_rate_latest_applicable_flag,
    coalesce(weighted.lending_interest_rate_latest, 0) as lending_interest_rate_latest,
    case when weighted.lending_interest_rate_latest_applicable_flag = 1 and weighted.lending_interest_rate_latest is null then 1 else 0 end as lending_interest_rate_latest_missing_flag,
    weighted.lending_interest_rate_latest_lag_28_applicable_flag as lending_interest_rate_latest_lag_28_applicable_flag,
    coalesce(weighted.lending_interest_rate_latest_lag_28, 0) as lending_interest_rate_latest_lag_28,
    case when weighted.lending_interest_rate_latest_lag_28_applicable_flag = 1 and weighted.lending_interest_rate_latest_lag_28 is null then 1 else 0 end as lending_interest_rate_latest_lag_28_missing_flag,
    weighted.source_legal_basis,
    weighted.source_license_type,
    weighted.source_review_status,
    weighted.source_legal_status_snapshot,
    weighted.lag_1_applicable_flag as lag_1_applicable_flag,

    coalesce(weighted.lag_1, 0) as lag_1,
    case when weighted.lag_1_applicable_flag = 1 and weighted.lag_1 is null then 1 else 0 end as lag_1_missing_flag,
    weighted.lag_7_applicable_flag as lag_7_applicable_flag,
    coalesce(weighted.lag_7, 0) as lag_7,
    case when weighted.lag_7_applicable_flag = 1 and weighted.lag_7 is null then 1 else 0 end as lag_7_missing_flag,
    weighted.lag_14_applicable_flag as lag_14_applicable_flag,
    coalesce(weighted.lag_14, 0) as lag_14,
    case when weighted.lag_14_applicable_flag = 1 and weighted.lag_14 is null then 1 else 0 end as lag_14_missing_flag,
    weighted.lag_28_applicable_flag as lag_28_applicable_flag,
    coalesce(weighted.lag_28, 0) as lag_28,
    case when weighted.lag_28_applicable_flag = 1 and weighted.lag_28 is null then 1 else 0 end as lag_28_missing_flag,
    weighted.target_lag_7_applicable_flag as target_lag_7_applicable_flag,
    coalesce(weighted.target_lag_7, 0) as target_lag_7,
    case when weighted.target_lag_7_applicable_flag = 1 and weighted.target_lag_7 is null then 1 else 0 end as target_lag_7_missing_flag,
    weighted.target_lag_14_applicable_flag as target_lag_14_applicable_flag,
    coalesce(weighted.target_lag_14, 0) as target_lag_14,
    case when weighted.target_lag_14_applicable_flag = 1 and weighted.target_lag_14 is null then 1 else 0 end as target_lag_14_missing_flag,
    weighted.target_lag_21_applicable_flag as target_lag_21_applicable_flag,
    coalesce(weighted.target_lag_21, 0) as target_lag_21,
    case when weighted.target_lag_21_applicable_flag = 1 and weighted.target_lag_21 is null then 1 else 0 end as target_lag_21_missing_flag,
    weighted.target_lag_28_applicable_flag as target_lag_28_applicable_flag,
    coalesce(weighted.target_lag_28, 0) as target_lag_28,
    case when weighted.target_lag_28_applicable_flag = 1 and weighted.target_lag_28 is null then 1 else 0 end as target_lag_28_missing_flag,
    weighted.rolling_mean_7_applicable_flag as rolling_mean_7_applicable_flag,
    coalesce(weighted.rolling_mean_7, 0) as rolling_mean_7,
    case when weighted.rolling_mean_7_applicable_flag = 1 and weighted.rolling_mean_7 is null then 1 else 0 end as rolling_mean_7_missing_flag,
    weighted.rolling_mean_14_applicable_flag as rolling_mean_14_applicable_flag,
    coalesce(weighted.rolling_mean_14, 0) as rolling_mean_14,
    case when weighted.rolling_mean_14_applicable_flag = 1 and weighted.rolling_mean_14 is null then 1 else 0 end as rolling_mean_14_missing_flag,
    weighted.rolling_mean_28_applicable_flag as rolling_mean_28_applicable_flag,
    coalesce(weighted.rolling_mean_28, 0) as rolling_mean_28,
    case when weighted.rolling_mean_28_applicable_flag = 1 and weighted.rolling_mean_28 is null then 1 else 0 end as rolling_mean_28_missing_flag,
    weighted.rolling_std_28_applicable_flag as rolling_std_28_applicable_flag,
    coalesce(weighted.rolling_std_28, 0) as rolling_std_28,
    case when weighted.rolling_std_28_applicable_flag = 1 and weighted.rolling_std_28 is null then 1 else 0 end as rolling_std_28_missing_flag,
    weighted.avg_selling_price_lag_1_applicable_flag as avg_selling_price_lag_1_applicable_flag,
    coalesce(weighted.avg_selling_price_lag_1, 0) as avg_selling_price_lag_1,
    case when weighted.avg_selling_price_lag_1_applicable_flag = 1 and weighted.avg_selling_price_lag_1 is null then 1 else 0 end as avg_selling_price_lag_1_missing_flag,
    weighted.avg_selling_price_lag_7_applicable_flag as avg_selling_price_lag_7_applicable_flag,
    coalesce(weighted.avg_selling_price_lag_7, 0) as avg_selling_price_lag_7,
    case when weighted.avg_selling_price_lag_7_applicable_flag = 1 and weighted.avg_selling_price_lag_7 is null then 1 else 0 end as avg_selling_price_lag_7_missing_flag,
    weighted.avg_selling_price_lag_28_applicable_flag as avg_selling_price_lag_28_applicable_flag,
    coalesce(weighted.avg_selling_price_lag_28, 0) as avg_selling_price_lag_28,
    case when weighted.avg_selling_price_lag_28_applicable_flag = 1 and weighted.avg_selling_price_lag_28 is null then 1 else 0 end as avg_selling_price_lag_28_missing_flag,
    weighted.observed_discount_amount_lag_1_applicable_flag as observed_discount_amount_lag_1_applicable_flag,
    coalesce(weighted.observed_discount_amount_lag_1, 0) as observed_discount_amount_lag_1,
    case when weighted.observed_discount_amount_lag_1_applicable_flag = 1 and weighted.observed_discount_amount_lag_1 is null then 1 else 0 end as observed_discount_amount_lag_1_missing_flag,
    weighted.observed_discount_amount_lag_7_applicable_flag as observed_discount_amount_lag_7_applicable_flag,
    coalesce(weighted.observed_discount_amount_lag_7, 0) as observed_discount_amount_lag_7,
    case when weighted.observed_discount_amount_lag_7_applicable_flag = 1 and weighted.observed_discount_amount_lag_7 is null then 1 else 0 end as observed_discount_amount_lag_7_missing_flag,
    weighted.observed_discount_amount_lag_28_applicable_flag as observed_discount_amount_lag_28_applicable_flag,
    coalesce(weighted.observed_discount_amount_lag_28, 0) as observed_discount_amount_lag_28,
    case when weighted.observed_discount_amount_lag_28_applicable_flag = 1 and weighted.observed_discount_amount_lag_28 is null then 1 else 0 end as observed_discount_amount_lag_28_missing_flag,
    weighted.observed_discount_amount_rolling_mean_7_applicable_flag as observed_discount_amount_rolling_mean_7_applicable_flag,
    coalesce(weighted.observed_discount_amount_rolling_mean_7, 0) as observed_discount_amount_rolling_mean_7,
    case when weighted.observed_discount_amount_rolling_mean_7_applicable_flag = 1 and weighted.observed_discount_amount_rolling_mean_7 is null then 1 else 0 end as observed_discount_amount_rolling_mean_7_missing_flag,
    weighted.observed_discount_amount_rolling_mean_28_applicable_flag as observed_discount_amount_rolling_mean_28_applicable_flag,
    coalesce(weighted.observed_discount_amount_rolling_mean_28, 0) as observed_discount_amount_rolling_mean_28,
    case when weighted.observed_discount_amount_rolling_mean_28_applicable_flag = 1 and weighted.observed_discount_amount_rolling_mean_28 is null then 1 else 0 end as observed_discount_amount_rolling_mean_28_missing_flag,
    weighted.promo_flag_lag_1_applicable_flag as promo_flag_lag_1_applicable_flag,
    coalesce(weighted.promo_flag_lag_1, false) as promo_flag_lag_1,
    case when weighted.promo_flag_lag_1_applicable_flag = 1 and weighted.promo_flag_lag_1 is null then 1 else 0 end as promo_flag_lag_1_missing_flag,
    weighted.promo_flag_lag_7_applicable_flag as promo_flag_lag_7_applicable_flag,
    coalesce(weighted.promo_flag_lag_7, false) as promo_flag_lag_7,
    case when weighted.promo_flag_lag_7_applicable_flag = 1 and weighted.promo_flag_lag_7 is null then 1 else 0 end as promo_flag_lag_7_missing_flag,
    weighted.promo_flag_lag_28_applicable_flag as promo_flag_lag_28_applicable_flag,
    coalesce(weighted.promo_flag_lag_28, false) as promo_flag_lag_28,
    case when weighted.promo_flag_lag_28_applicable_flag = 1 and weighted.promo_flag_lag_28 is null then 1 else 0 end as promo_flag_lag_28_missing_flag,
    weighted.promo_rate_7_applicable_flag as promo_rate_7_applicable_flag,
    coalesce(weighted.promo_rate_7, 0) as promo_rate_7,
    case when weighted.promo_rate_7_applicable_flag = 1 and weighted.promo_rate_7 is null then 1 else 0 end as promo_rate_7_missing_flag,
    weighted.promo_rate_28_applicable_flag as promo_rate_28_applicable_flag,
    coalesce(weighted.promo_rate_28, 0) as promo_rate_28,
    case when weighted.promo_rate_28_applicable_flag = 1 and weighted.promo_rate_28 is null then 1 else 0 end as promo_rate_28_missing_flag,
    weighted.activity_flag_lag_1_applicable_flag as activity_flag_lag_1_applicable_flag,
    coalesce(weighted.activity_flag_lag_1, false) as activity_flag_lag_1,
    case when weighted.activity_flag_lag_1_applicable_flag = 1 and weighted.activity_flag_lag_1 is null then 1 else 0 end as activity_flag_lag_1_missing_flag,
    weighted.activity_flag_lag_7_applicable_flag as activity_flag_lag_7_applicable_flag,
    coalesce(weighted.activity_flag_lag_7, false) as activity_flag_lag_7,
    case when weighted.activity_flag_lag_7_applicable_flag = 1 and weighted.activity_flag_lag_7 is null then 1 else 0 end as activity_flag_lag_7_missing_flag,
    weighted.activity_flag_lag_28_applicable_flag as activity_flag_lag_28_applicable_flag,
    coalesce(weighted.activity_flag_lag_28, false) as activity_flag_lag_28,
    case when weighted.activity_flag_lag_28_applicable_flag = 1 and weighted.activity_flag_lag_28 is null then 1 else 0 end as activity_flag_lag_28_missing_flag,
    weighted.activity_rate_7_applicable_flag as activity_rate_7_applicable_flag,
    coalesce(weighted.activity_rate_7, 0) as activity_rate_7,
    case when weighted.activity_rate_7_applicable_flag = 1 and weighted.activity_rate_7 is null then 1 else 0 end as activity_rate_7_missing_flag,
    weighted.activity_rate_28_applicable_flag as activity_rate_28_applicable_flag,
    coalesce(weighted.activity_rate_28, 0) as activity_rate_28,
    case when weighted.activity_rate_28_applicable_flag = 1 and weighted.activity_rate_28 is null then 1 else 0 end as activity_rate_28_missing_flag,
    weighted.observed_stockout_flag_lag_1_applicable_flag as observed_stockout_flag_lag_1_applicable_flag,
    coalesce(weighted.observed_stockout_flag_lag_1, false) as observed_stockout_flag_lag_1,
    case when weighted.observed_stockout_flag_lag_1_applicable_flag = 1 and weighted.observed_stockout_flag_lag_1 is null then 1 else 0 end as observed_stockout_flag_lag_1_missing_flag,
    weighted.observed_stockout_flag_lag_7_applicable_flag as observed_stockout_flag_lag_7_applicable_flag,
    coalesce(weighted.observed_stockout_flag_lag_7, false) as observed_stockout_flag_lag_7,
    case when weighted.observed_stockout_flag_lag_7_applicable_flag = 1 and weighted.observed_stockout_flag_lag_7 is null then 1 else 0 end as observed_stockout_flag_lag_7_missing_flag,
    weighted.observed_stockout_flag_lag_28_applicable_flag as observed_stockout_flag_lag_28_applicable_flag,
    coalesce(weighted.observed_stockout_flag_lag_28, false) as observed_stockout_flag_lag_28,
    case when weighted.observed_stockout_flag_lag_28_applicable_flag = 1 and weighted.observed_stockout_flag_lag_28 is null then 1 else 0 end as observed_stockout_flag_lag_28_missing_flag,
    weighted.observed_stockout_rate_7_applicable_flag as observed_stockout_rate_7_applicable_flag,
    coalesce(weighted.observed_stockout_rate_7, 0) as observed_stockout_rate_7,
    case when weighted.observed_stockout_rate_7_applicable_flag = 1 and weighted.observed_stockout_rate_7 is null then 1 else 0 end as observed_stockout_rate_7_missing_flag,
    weighted.observed_stockout_rate_28_applicable_flag as observed_stockout_rate_28_applicable_flag,
    coalesce(weighted.observed_stockout_rate_28, 0) as observed_stockout_rate_28,
    case when weighted.observed_stockout_rate_28_applicable_flag = 1 and weighted.observed_stockout_rate_28 is null then 1 else 0 end as observed_stockout_rate_28_missing_flag,
    weighted.same_dow_mean_4w_applicable_flag as same_dow_mean_4w_applicable_flag,
    coalesce(weighted.same_dow_mean_4w, 0) as same_dow_mean_4w,
    case when weighted.same_dow_mean_4w_applicable_flag = 1 and weighted.same_dow_mean_4w is null then 1 else 0 end as same_dow_mean_4w_missing_flag,
    weighted.target_same_dow_mean_4w_applicable_flag as target_same_dow_mean_4w_applicable_flag,
    coalesce(weighted.target_same_dow_mean_4w, 0) as target_same_dow_mean_4w,
    case when weighted.target_same_dow_mean_4w_applicable_flag = 1 and weighted.target_same_dow_mean_4w is null then 1 else 0 end as target_same_dow_mean_4w_missing_flag,
    weighted.naive_last_value_applicable_flag as naive_last_value_applicable_flag,
    coalesce(weighted.naive_last_value, 0) as naive_last_value,
    case when weighted.naive_last_value_applicable_flag = 1 and weighted.naive_last_value is null then 1 else 0 end as naive_last_value_missing_flag,
    weighted.seasonal_naive_d7_applicable_flag as seasonal_naive_d7_applicable_flag,
    coalesce(weighted.seasonal_naive_d7, 0) as seasonal_naive_d7,
    case when weighted.seasonal_naive_d7_applicable_flag = 1 and weighted.seasonal_naive_d7 is null then 1 else 0 end as seasonal_naive_d7_missing_flag,
    weighted.target_seasonal_naive_d7_applicable_flag as target_seasonal_naive_d7_applicable_flag,
    coalesce(weighted.target_seasonal_naive_d7, 0) as target_seasonal_naive_d7,
    case when weighted.target_seasonal_naive_d7_applicable_flag = 1 and weighted.target_seasonal_naive_d7 is null then 1 else 0 end as target_seasonal_naive_d7_missing_flag,
    weighted.moving_average_7_applicable_flag as moving_average_7_applicable_flag,
    coalesce(weighted.moving_average_7, 0) as moving_average_7,
    case when weighted.moving_average_7_applicable_flag = 1 and weighted.moving_average_7 is null then 1 else 0 end as moving_average_7_missing_flag,
    weighted.moving_average_28_applicable_flag as moving_average_28_applicable_flag,
    coalesce(weighted.moving_average_28, 0) as moving_average_28,
    case when weighted.moving_average_28_applicable_flag = 1 and weighted.moving_average_28 is null then 1 else 0 end as moving_average_28_missing_flag,
    weighted.sample_weight_source,
    weighted.sample_weight_business,
    weighted.is_primary_eval_dataset,
    weighted.gold_run_id
from weighted
)
select
    legacy_panel.* exclude (
{% for base in feature_status_bases %}
        {{ base }}_applicable_flag,
        {{ base }}_missing_flag{{ "," if not loop.last }}
{% endfor %}
    ),
{% for family_name, bases in data_quality_families %}
    (
{% for base in bases %}
        case when legacy_panel.{{ base }}_applicable_flag = 0 then 1 else 0 end{{ " +" if not loop.last }}
{% endfor %}
    ) as data_quality_{{ family_name }}_unavailable_count,
    (
{% for base in bases %}
        legacy_panel.{{ base }}_missing_flag{{ " +" if not loop.last }}
{% endfor %}
    ) as data_quality_{{ family_name }}_missing_count{{ "," if not loop.last }}
{% endfor %}
from legacy_panel
