{% macro praedixa_gold_feature_slice(base_relation, slice_filter_sql, split_scope_filter_sql, split_strategy) %}
with base as (
    select *
    from {{ base_relation }}
    where {{ slice_filter_sql }}
),
base_panel as (
    select
        dataset_source,
        source_partition,
        source_run_id,
        series_id,
        dt,
        target_dt,
        location_id,
        product_id,
        region_id,
        org_group_id,
        category_level_1,
        category_level_2,
        category_level_3,
        drive_through_flag,
        delivery_flag,
        pickup_flag,
        product_family,
        product_subfamily,
        is_observed_row,
        day_complete_flag,
        observed_stockout_flag,
        observed_stockout_available,
        current_day_demand_qty,
        true_zero_demand_flag,
        target_semantics,
        censor_flag,
        target_source,
        label_quality_score,
        usable_for_training_flag,
        observed_revenue_net,
        observed_discount_amount,
        promo_flag,
        holiday_flag,
        activity_flag,
        bridge_day_flag,
        pre_holiday_flag,
        post_holiday_flag,
        month_start_flag,
        month_end_flag,
        weather_temperature,
        weather_temperature_min,
        weather_temperature_max,
        weather_precipitation,
        weather_humidity,
        weather_wind_level,
        lending_interest_rate_latest,
        vertical_level_1,
        vertical_level_2,
        country_code,
        region_code,
        city_name,
        source_legal_basis,
        source_license_type,
        source_review_status,
        source_legal_status_snapshot,
        source_role,
        is_synthetic_source,
        gold_run_id
    from base
),
window_inputs as (
    select
        dataset_source,
        dt,
        target_dt,
        location_id,
        product_id,
        is_observed_row,
        current_day_demand_qty,
        true_zero_demand_flag,
        observed_revenue_net,
        day_complete_flag,
        target_semantics,
        censor_flag,
        target_source,
        label_quality_score,
        usable_for_training_flag,
        observed_discount_amount,
        promo_flag,
        activity_flag,
        observed_stockout_flag,
        weather_temperature,
        weather_temperature_min,
        weather_temperature_max,
        weather_precipitation,
        weather_humidity,
        weather_wind_level,
        lending_interest_rate_latest,
        holiday_flag,
        bridge_day_flag,
        pre_holiday_flag,
        post_holiday_flag
    from base_panel
),
window_lagged as (
    select
        *,
        lead(current_day_demand_qty, 1) over series_window as target_demand_qty_d_plus_1,
        lead(target_semantics, 1) over series_window as target_semantics_d_plus_1,
        lead(censor_flag, 1) over series_window as censor_flag_d_plus_1,
        lead(target_source, 1) over series_window as target_source_d_plus_1,
        lead(label_quality_score, 1) over series_window as label_quality_score_d_plus_1,
        lead(usable_for_training_flag, 1) over series_window as usable_for_training_flag_d_plus_1,
        lead(true_zero_demand_flag, 1) over series_window as target_true_zero_demand_flag,
        sum(case when is_observed_row then 1 else 0 end) over series_window as history_available_days,
        lag(current_day_demand_qty, 1) over series_window as lag_1,
        lag(current_day_demand_qty, 2) over series_window as lag_2,
        lag(current_day_demand_qty, 3) over series_window as lag_3,
        lag(current_day_demand_qty, 4) over series_window as lag_4,
        lag(current_day_demand_qty, 5) over series_window as lag_5,
        lag(current_day_demand_qty, 6) over series_window as lag_6,
        lag(current_day_demand_qty, 7) over series_window as lag_7,
        lag(current_day_demand_qty, 14) over series_window as lag_14,
        lag(current_day_demand_qty, 21) over series_window as lag_21_same_dow,
        lag(current_day_demand_qty, 28) over series_window as lag_28,
        current_day_demand_qty as target_lag_1,
        lag(current_day_demand_qty, 1) over series_window as target_lag_2,
        lag(current_day_demand_qty, 2) over series_window as target_lag_3,
        lag(current_day_demand_qty, 3) over series_window as target_lag_4,
        lag(current_day_demand_qty, 4) over series_window as target_lag_5,
        lag(current_day_demand_qty, 5) over series_window as target_lag_6,
        lag(current_day_demand_qty, 6) over series_window as target_lag_7,
        lag(current_day_demand_qty, 13) over series_window as target_lag_14,
        lag(current_day_demand_qty, 20) over series_window as target_lag_21,
        lag(current_day_demand_qty, 27) over series_window as target_lag_28,
        avg(current_day_demand_qty) over rolling_7 as rolling_mean_7,
        avg(current_day_demand_qty) over rolling_14 as rolling_mean_14,
        avg(current_day_demand_qty) over rolling_28 as rolling_mean_28,
        stddev_samp(current_day_demand_qty) over rolling_28 as rolling_std_28,
        current_day_demand_qty as naive_last_value,
        lag(observed_revenue_net, 1) over series_window as observed_revenue_net_lag_1,
        lag(observed_revenue_net, 2) over series_window as observed_revenue_net_lag_2,
        lag(observed_revenue_net, 3) over series_window as observed_revenue_net_lag_3,
        lag(observed_revenue_net, 4) over series_window as observed_revenue_net_lag_4,
        lag(observed_revenue_net, 5) over series_window as observed_revenue_net_lag_5,
        lag(observed_revenue_net, 6) over series_window as observed_revenue_net_lag_6,
        lag(observed_revenue_net, 7) over series_window as observed_revenue_net_lag_7,
        lag(observed_revenue_net, 14) over series_window as observed_revenue_net_lag_14,
        lag(observed_revenue_net, 28) over series_window as observed_revenue_net_lag_28,
        lag(observed_discount_amount, 1) over series_window as observed_discount_amount_lag_1,
        lag(observed_discount_amount, 2) over series_window as observed_discount_amount_lag_2,
        lag(observed_discount_amount, 3) over series_window as observed_discount_amount_lag_3,
        lag(observed_discount_amount, 4) over series_window as observed_discount_amount_lag_4,
        lag(observed_discount_amount, 5) over series_window as observed_discount_amount_lag_5,
        lag(observed_discount_amount, 6) over series_window as observed_discount_amount_lag_6,
        lag(observed_discount_amount, 7) over series_window as observed_discount_amount_lag_7,
        lag(observed_discount_amount, 14) over series_window as observed_discount_amount_lag_14,
        lag(observed_discount_amount, 28) over series_window as observed_discount_amount_lag_28,
        avg(observed_discount_amount) over rolling_7 as observed_discount_amount_rolling_mean_7,
        avg(observed_discount_amount) over rolling_28 as observed_discount_amount_rolling_mean_28,
        lag(promo_flag, 1) over series_window as promo_flag_lag_1,
        lag(promo_flag, 2) over series_window as promo_flag_lag_2,
        lag(promo_flag, 3) over series_window as promo_flag_lag_3,
        lag(promo_flag, 4) over series_window as promo_flag_lag_4,
        lag(promo_flag, 5) over series_window as promo_flag_lag_5,
        lag(promo_flag, 6) over series_window as promo_flag_lag_6,
        lag(promo_flag, 7) over series_window as promo_flag_lag_7,
        lag(promo_flag, 14) over series_window as promo_flag_lag_14,
        lag(promo_flag, 28) over series_window as promo_flag_lag_28,
        avg(cast(promo_flag as double)) over rolling_7 as promo_rate_7,
        avg(cast(promo_flag as double)) over rolling_28 as promo_rate_28,
        lag(activity_flag, 1) over series_window as activity_flag_lag_1,
        lag(activity_flag, 2) over series_window as activity_flag_lag_2,
        lag(activity_flag, 3) over series_window as activity_flag_lag_3,
        lag(activity_flag, 4) over series_window as activity_flag_lag_4,
        lag(activity_flag, 5) over series_window as activity_flag_lag_5,
        lag(activity_flag, 6) over series_window as activity_flag_lag_6,
        lag(activity_flag, 7) over series_window as activity_flag_lag_7,
        lag(activity_flag, 14) over series_window as activity_flag_lag_14,
        lag(activity_flag, 28) over series_window as activity_flag_lag_28,
        avg(cast(activity_flag as double)) over rolling_7 as activity_rate_7,
        avg(cast(activity_flag as double)) over rolling_28 as activity_rate_28,
        lag(observed_stockout_flag, 1) over series_window as observed_stockout_flag_lag_1,
        lag(observed_stockout_flag, 2) over series_window as observed_stockout_flag_lag_2,
        lag(observed_stockout_flag, 3) over series_window as observed_stockout_flag_lag_3,
        lag(observed_stockout_flag, 4) over series_window as observed_stockout_flag_lag_4,
        lag(observed_stockout_flag, 5) over series_window as observed_stockout_flag_lag_5,
        lag(observed_stockout_flag, 6) over series_window as observed_stockout_flag_lag_6,
        lag(observed_stockout_flag, 7) over series_window as observed_stockout_flag_lag_7,
        lag(observed_stockout_flag, 14) over series_window as observed_stockout_flag_lag_14,
        lag(observed_stockout_flag, 28) over series_window as observed_stockout_flag_lag_28,
        avg(cast(observed_stockout_flag as double)) over rolling_7 as observed_stockout_rate_7,
        avg(cast(observed_stockout_flag as double)) over rolling_28 as observed_stockout_rate_28,
        lag(censor_flag, 1) over series_window as censor_flag_lag_1,
        lag(censor_flag, 2) over series_window as censor_flag_lag_2,
        lag(censor_flag, 3) over series_window as censor_flag_lag_3,
        lag(censor_flag, 4) over series_window as censor_flag_lag_4,
        lag(censor_flag, 5) over series_window as censor_flag_lag_5,
        lag(censor_flag, 6) over series_window as censor_flag_lag_6,
        lag(censor_flag, 7) over series_window as censor_flag_lag_7,
        lag(censor_flag, 14) over series_window as censor_flag_lag_14,
        lag(censor_flag, 28) over series_window as censor_flag_lag_28,
        avg(cast(censor_flag as double)) over rolling_7 as censor_rate_7,
        avg(cast(censor_flag as double)) over rolling_28 as censor_rate_28,
        lag(label_quality_score, 1) over series_window as label_quality_score_lag_1,
        lag(label_quality_score, 2) over series_window as label_quality_score_lag_2,
        lag(label_quality_score, 3) over series_window as label_quality_score_lag_3,
        lag(label_quality_score, 4) over series_window as label_quality_score_lag_4,
        lag(label_quality_score, 5) over series_window as label_quality_score_lag_5,
        lag(label_quality_score, 6) over series_window as label_quality_score_lag_6,
        lag(label_quality_score, 7) over series_window as label_quality_score_lag_7,
        lag(label_quality_score, 14) over series_window as label_quality_score_lag_14,
        lag(label_quality_score, 28) over series_window as label_quality_score_lag_28,
        avg(label_quality_score) over rolling_7 as label_quality_score_rolling_mean_7,
        avg(label_quality_score) over rolling_28 as label_quality_score_rolling_mean_28,
        lag(day_complete_flag, 1) over series_window as day_complete_flag_lag_1,
        lag(day_complete_flag, 2) over series_window as day_complete_flag_lag_2,
        lag(day_complete_flag, 3) over series_window as day_complete_flag_lag_3,
        lag(day_complete_flag, 4) over series_window as day_complete_flag_lag_4,
        lag(day_complete_flag, 5) over series_window as day_complete_flag_lag_5,
        lag(day_complete_flag, 6) over series_window as day_complete_flag_lag_6,
        lag(day_complete_flag, 7) over series_window as day_complete_flag_lag_7,
        lag(day_complete_flag, 14) over series_window as day_complete_flag_lag_14,
        lag(day_complete_flag, 28) over series_window as day_complete_flag_lag_28,
        avg(cast(day_complete_flag as double)) over rolling_7 as day_complete_rate_7,
        avg(cast(day_complete_flag as double)) over rolling_28 as day_complete_rate_28,
        lag(weather_temperature, 1) over series_window as weather_temperature_lag_1,
        lag(weather_temperature, 2) over series_window as weather_temperature_lag_2,
        lag(weather_temperature, 3) over series_window as weather_temperature_lag_3,
        lag(weather_temperature, 4) over series_window as weather_temperature_lag_4,
        lag(weather_temperature, 5) over series_window as weather_temperature_lag_5,
        lag(weather_temperature, 6) over series_window as weather_temperature_lag_6,
        lag(weather_temperature, 7) over series_window as weather_temperature_lag_7,
        lag(weather_temperature, 14) over series_window as weather_temperature_lag_14,
        avg(weather_temperature) over rolling_7 as weather_temperature_rolling_mean_7,
        avg(weather_temperature) over rolling_28 as weather_temperature_rolling_mean_28,
        lag(weather_temperature_min, 1) over series_window as weather_temperature_min_lag_1,
        lag(weather_temperature_min, 2) over series_window as weather_temperature_min_lag_2,
        lag(weather_temperature_min, 3) over series_window as weather_temperature_min_lag_3,
        lag(weather_temperature_min, 4) over series_window as weather_temperature_min_lag_4,
        lag(weather_temperature_min, 5) over series_window as weather_temperature_min_lag_5,
        lag(weather_temperature_min, 6) over series_window as weather_temperature_min_lag_6,
        lag(weather_temperature_min, 7) over series_window as weather_temperature_min_lag_7,
        lag(weather_temperature_min, 14) over series_window as weather_temperature_min_lag_14,
        lag(weather_temperature_max, 1) over series_window as weather_temperature_max_lag_1,
        lag(weather_temperature_max, 2) over series_window as weather_temperature_max_lag_2,
        lag(weather_temperature_max, 3) over series_window as weather_temperature_max_lag_3,
        lag(weather_temperature_max, 4) over series_window as weather_temperature_max_lag_4,
        lag(weather_temperature_max, 5) over series_window as weather_temperature_max_lag_5,
        lag(weather_temperature_max, 6) over series_window as weather_temperature_max_lag_6,
        lag(weather_temperature_max, 7) over series_window as weather_temperature_max_lag_7,
        lag(weather_temperature_max, 14) over series_window as weather_temperature_max_lag_14,
        lag(weather_precipitation, 1) over series_window as weather_precipitation_lag_1,
        lag(weather_precipitation, 2) over series_window as weather_precipitation_lag_2,
        lag(weather_precipitation, 3) over series_window as weather_precipitation_lag_3,
        lag(weather_precipitation, 4) over series_window as weather_precipitation_lag_4,
        lag(weather_precipitation, 5) over series_window as weather_precipitation_lag_5,
        lag(weather_precipitation, 6) over series_window as weather_precipitation_lag_6,
        lag(weather_precipitation, 7) over series_window as weather_precipitation_lag_7,
        lag(weather_precipitation, 14) over series_window as weather_precipitation_lag_14,
        avg(weather_precipitation) over rolling_7 as weather_precipitation_rolling_mean_7,
        avg(weather_precipitation) over rolling_28 as weather_precipitation_rolling_mean_28,
        lag(weather_humidity, 1) over series_window as weather_humidity_lag_1,
        lag(weather_humidity, 2) over series_window as weather_humidity_lag_2,
        lag(weather_humidity, 3) over series_window as weather_humidity_lag_3,
        lag(weather_humidity, 4) over series_window as weather_humidity_lag_4,
        lag(weather_humidity, 5) over series_window as weather_humidity_lag_5,
        lag(weather_humidity, 6) over series_window as weather_humidity_lag_6,
        lag(weather_humidity, 7) over series_window as weather_humidity_lag_7,
        lag(weather_humidity, 14) over series_window as weather_humidity_lag_14,
        avg(weather_humidity) over rolling_7 as weather_humidity_rolling_mean_7,
        lag(weather_wind_level, 1) over series_window as weather_wind_level_lag_1,
        lag(weather_wind_level, 2) over series_window as weather_wind_level_lag_2,
        lag(weather_wind_level, 3) over series_window as weather_wind_level_lag_3,
        lag(weather_wind_level, 4) over series_window as weather_wind_level_lag_4,
        lag(weather_wind_level, 5) over series_window as weather_wind_level_lag_5,
        lag(weather_wind_level, 6) over series_window as weather_wind_level_lag_6,
        lag(weather_wind_level, 7) over series_window as weather_wind_level_lag_7,
        lag(weather_wind_level, 14) over series_window as weather_wind_level_lag_14,
        avg(weather_wind_level) over rolling_7 as weather_wind_level_rolling_mean_7,
        lag(lending_interest_rate_latest, 28) over series_window as lending_interest_rate_latest_lag_28,
        lead(holiday_flag, 1) over series_window as target_holiday_flag
    from window_inputs
    window
        series_window as (
            partition by dataset_source, location_id, product_id
            order by dt
        ),
        rolling_7 as (
            partition by dataset_source, location_id, product_id
            order by dt
            rows between 6 preceding and current row
        ),
        rolling_14 as (
            partition by dataset_source, location_id, product_id
            order by dt
            rows between 13 preceding and current row
        ),
        rolling_28 as (
            partition by dataset_source, location_id, product_id
            order by dt
            rows between 27 preceding and current row
        )
),
window_features as (
    select
        dataset_source,
        dt,
        target_dt,
        location_id,
        product_id,
        target_demand_qty_d_plus_1,
        target_semantics_d_plus_1,
        censor_flag_d_plus_1,
        target_source_d_plus_1,
        label_quality_score_d_plus_1,
        usable_for_training_flag_d_plus_1,
        target_true_zero_demand_flag,
        history_available_days,
        lag_1,
        lag_2,
        lag_3,
        lag_4,
        lag_5,
        lag_6,
        lag_7,
        lag_14,
        lag_28,
        target_lag_1,
        target_lag_2,
        target_lag_3,
        target_lag_4,
        target_lag_5,
        target_lag_6,
        target_lag_7,
        target_lag_14,
        target_lag_21,
        target_lag_28,
        rolling_mean_7,
        rolling_mean_14,
        rolling_mean_28,
        rolling_std_28,
        observed_discount_amount_lag_1,
        observed_discount_amount_lag_2,
        observed_discount_amount_lag_3,
        observed_discount_amount_lag_4,
        observed_discount_amount_lag_5,
        observed_discount_amount_lag_6,
        observed_discount_amount_lag_7,
        observed_discount_amount_lag_14,
        observed_discount_amount_lag_28,
        observed_discount_amount_rolling_mean_7,
        observed_discount_amount_rolling_mean_28,
        promo_flag_lag_1,
        promo_flag_lag_2,
        promo_flag_lag_3,
        promo_flag_lag_4,
        promo_flag_lag_5,
        promo_flag_lag_6,
        promo_flag_lag_7,
        promo_flag_lag_14,
        promo_flag_lag_28,
        promo_rate_7,
        promo_rate_28,
        activity_flag_lag_1,
        activity_flag_lag_2,
        activity_flag_lag_3,
        activity_flag_lag_4,
        activity_flag_lag_5,
        activity_flag_lag_6,
        activity_flag_lag_7,
        activity_flag_lag_14,
        activity_flag_lag_28,
        activity_rate_7,
        activity_rate_28,
        observed_stockout_flag_lag_1,
        observed_stockout_flag_lag_2,
        observed_stockout_flag_lag_3,
        observed_stockout_flag_lag_4,
        observed_stockout_flag_lag_5,
        observed_stockout_flag_lag_6,
        observed_stockout_flag_lag_7,
        observed_stockout_flag_lag_14,
        observed_stockout_flag_lag_28,
        observed_stockout_rate_7,
        observed_stockout_rate_28,
        censor_flag_lag_1,
        censor_flag_lag_2,
        censor_flag_lag_3,
        censor_flag_lag_4,
        censor_flag_lag_5,
        censor_flag_lag_6,
        censor_flag_lag_7,
        censor_flag_lag_14,
        censor_flag_lag_28,
        censor_rate_7,
        censor_rate_28,
        label_quality_score_lag_1,
        label_quality_score_lag_2,
        label_quality_score_lag_3,
        label_quality_score_lag_4,
        label_quality_score_lag_5,
        label_quality_score_lag_6,
        label_quality_score_lag_7,
        label_quality_score_lag_14,
        label_quality_score_lag_28,
        label_quality_score_rolling_mean_7,
        label_quality_score_rolling_mean_28,
        day_complete_flag_lag_1,
        day_complete_flag_lag_2,
        day_complete_flag_lag_3,
        day_complete_flag_lag_4,
        day_complete_flag_lag_5,
        day_complete_flag_lag_6,
        day_complete_flag_lag_7,
        day_complete_flag_lag_14,
        day_complete_flag_lag_28,
        day_complete_rate_7,
        day_complete_rate_28,
        (
            coalesce(lag_7, 0.0)
            + coalesce(lag_14, 0.0)
            + coalesce(lag_21_same_dow, 0.0)
            + coalesce(lag_28, 0.0)
        ) / nullif(
            (case when lag_7 is not null then 1 else 0 end)
            + (case when lag_14 is not null then 1 else 0 end)
            + (case when lag_21_same_dow is not null then 1 else 0 end)
            + (case when lag_28 is not null then 1 else 0 end),
            0
        ) as same_dow_mean_4w,
        (
            coalesce(target_lag_7, 0.0)
            + coalesce(target_lag_14, 0.0)
            + coalesce(target_lag_21, 0.0)
            + coalesce(target_lag_28, 0.0)
        ) / nullif(
            (case when target_lag_7 is not null then 1 else 0 end)
            + (case when target_lag_14 is not null then 1 else 0 end)
            + (case when target_lag_21 is not null then 1 else 0 end)
            + (case when target_lag_28 is not null then 1 else 0 end),
            0
        ) as target_same_dow_mean_4w,
        naive_last_value,
        observed_revenue_net_lag_1,
        observed_revenue_net_lag_2,
        observed_revenue_net_lag_3,
        observed_revenue_net_lag_4,
        observed_revenue_net_lag_5,
        observed_revenue_net_lag_6,
        observed_revenue_net_lag_7,
        observed_revenue_net_lag_14,
        observed_revenue_net_lag_28,
        lag_7 as seasonal_naive_d7,
        target_lag_7 as target_seasonal_naive_d7,
        rolling_mean_7 as moving_average_7,
        rolling_mean_28 as moving_average_28,
        weather_temperature as weather_temperature_lag_0,
        weather_temperature_lag_1,
        weather_temperature_lag_2,
        weather_temperature_lag_3,
        weather_temperature_lag_4,
        weather_temperature_lag_5,
        weather_temperature_lag_6,
        weather_temperature_lag_7,
        weather_temperature_lag_14,
        weather_temperature_rolling_mean_7,
        weather_temperature_rolling_mean_28,
        weather_temperature_min as weather_temperature_min_lag_0,
        weather_temperature_min_lag_1,
        weather_temperature_min_lag_2,
        weather_temperature_min_lag_3,
        weather_temperature_min_lag_4,
        weather_temperature_min_lag_5,
        weather_temperature_min_lag_6,
        weather_temperature_min_lag_7,
        weather_temperature_min_lag_14,
        weather_temperature_max as weather_temperature_max_lag_0,
        weather_temperature_max_lag_1,
        weather_temperature_max_lag_2,
        weather_temperature_max_lag_3,
        weather_temperature_max_lag_4,
        weather_temperature_max_lag_5,
        weather_temperature_max_lag_6,
        weather_temperature_max_lag_7,
        weather_temperature_max_lag_14,
        weather_precipitation as weather_precipitation_lag_0,
        weather_precipitation_lag_1,
        weather_precipitation_lag_2,
        weather_precipitation_lag_3,
        weather_precipitation_lag_4,
        weather_precipitation_lag_5,
        weather_precipitation_lag_6,
        weather_precipitation_lag_7,
        weather_precipitation_lag_14,
        weather_precipitation_rolling_mean_7,
        weather_precipitation_rolling_mean_28,
        weather_humidity as weather_humidity_lag_0,
        weather_humidity_lag_1,
        weather_humidity_lag_2,
        weather_humidity_lag_3,
        weather_humidity_lag_4,
        weather_humidity_lag_5,
        weather_humidity_lag_6,
        weather_humidity_lag_7,
        weather_humidity_lag_14,
        weather_humidity_rolling_mean_7,
        weather_wind_level as weather_wind_level_lag_0,
        weather_wind_level_lag_1,
        weather_wind_level_lag_2,
        weather_wind_level_lag_3,
        weather_wind_level_lag_4,
        weather_wind_level_lag_5,
        weather_wind_level_lag_6,
        weather_wind_level_lag_7,
        weather_wind_level_lag_14,
        weather_wind_level_rolling_mean_7,
        lending_interest_rate_latest_lag_28,
        target_holiday_flag
    from window_lagged
),
eligible as (
    select
        *,
        case
            when target_demand_qty_d_plus_1 >= 0
             and target_lag_7 >= 0
            then ln(1.0 + target_demand_qty_d_plus_1) - ln(1.0 + target_lag_7)
            else null
        end as target_delta_log_wow_d_plus_1,
        case
            when target_lag_1 is not null and target_lag_7 is not null
            then 0.5 * target_lag_1 + 0.5 * target_lag_7
            else coalesce(target_lag_1, target_lag_7)
        end as field_baseline_blend_lag_1_lag_7_d_plus_1,
        cast(strftime(target_dt, '%u') as integer) - 1 as target_day_of_week,
        cast(strftime(target_dt, '%d') as integer) as target_day_of_month,
        cast(strftime(target_dt, '%V') as integer) as target_week_of_year,
        cast(strftime(target_dt, '%m') as integer) as target_month,
        cast(ceil(cast(strftime(target_dt, '%m') as integer) / 3.0) as integer) as target_quarter,
        cast(strftime(target_dt, '%Y') as integer) as target_year,
        case
            when history_available_days <= 0 then '0'
            when history_available_days <= 7 then '1_7'
            when history_available_days <= 14 then '8_14'
            when history_available_days <= 28 then '15_28'
            when history_available_days <= 56 then '29_56'
            else '56_plus'
        end as cold_start_bucket,
        (cast(strftime(target_dt, '%u') as integer) in (6, 7)) as target_weekend_flag,
        sin(2 * pi() * (cast(strftime(target_dt, '%u') as double) - 1) / 7.0) as sin_target_day_of_week,
        cos(2 * pi() * (cast(strftime(target_dt, '%u') as double) - 1) / 7.0) as cos_target_day_of_week,
        sin(2 * pi() * cast(strftime(target_dt, '%V') as double) / 53.0) as sin_target_week_of_year,
        cos(2 * pi() * cast(strftime(target_dt, '%V') as double) / 53.0) as cos_target_week_of_year,
        sin(2 * pi() * cast(strftime(target_dt, '%m') as double) / 12.0) as sin_target_month,
        cos(2 * pi() * cast(strftime(target_dt, '%m') as double) / 12.0) as cos_target_month
    from window_features
    where target_demand_qty_d_plus_1 is not null
),
split_scope_dates as (
    select distinct
        dataset_source,
        dt
    from {{ base_relation }}
    where {{ split_scope_filter_sql }}
),
date_ranks as (
    select
        dataset_source,
        dt,
        row_number() over (partition by dataset_source order by dt) as date_rank,
        count(*) over (partition by dataset_source) as date_count
    from split_scope_dates
)
{% if split_strategy in ["bakery_test_only", "bakery_chrono_75_25_test_3mo"] %}
,
bakery_dataset_bounds as (
    select
        max(dt) as max_dt
    from {{ ref('silver_bakery_daily_product_demand') }}
),
bakery_pretest_dates as (
    select distinct
        split_scope_dates.dataset_source,
        split_scope_dates.dt
    from split_scope_dates
    cross join bakery_dataset_bounds
    where split_scope_dates.dt <= bakery_dataset_bounds.max_dt - interval {{ env_var('PRAEDIXA_GOLD_BAKERY_TEST_MONTHS', '3') | int }} month
),
bakery_pretest_date_ranks as (
    select
        dataset_source,
        dt,
        row_number() over (partition by dataset_source order by dt) as date_rank,
        count(*) over (partition by dataset_source) as date_count
    from bakery_pretest_dates
)
{% endif %}
,
split_labeled as (
    select
        eligible.*,
        {% if split_strategy == "bakery_test_only" %}
        case
            when eligible.dt > bakery_dataset_bounds.max_dt - interval {{ env_var('PRAEDIXA_GOLD_BAKERY_TEST_MONTHS', '3') | int }} month then 'test'
            else null
        end as split_bucket
        {% elif split_strategy == "bakery_chrono_75_25_test_3mo" %}
        case
            when eligible.dt > bakery_dataset_bounds.max_dt - interval {{ env_var('PRAEDIXA_GOLD_BAKERY_TEST_MONTHS', '3') | int }} month then 'test'
            when bakery_pretest_ranks.date_rank <= greatest(1, cast(floor(bakery_pretest_ranks.date_count * 0.75) as bigint)) then 'train'
            else 'val'
        end as split_bucket
        {% elif split_strategy == "pilot_ready_chrono_60_20_20" %}
        case
            when ranks.date_rank <= cast(floor(ranks.date_count * 0.6) as bigint) then 'train'
            when ranks.date_rank <= cast(floor(ranks.date_count * 0.8) as bigint) then 'val'
            else 'test'
        end as split_bucket
        {% elif split_strategy == "chrono_60_40" %}
        case
            when ranks.date_rank <= cast(floor(ranks.date_count * 0.6) as bigint) then 'train'
            else 'val'
        end as split_bucket
        {% elif split_strategy == "train_only" %}
        'train' as split_bucket
        {% else %}
        cast(null as varchar) as split_bucket
        {% endif %}
    from eligible
    {% if split_strategy in ["chrono_60_40", "pilot_ready_chrono_60_20_20"] %}
    inner join date_ranks as ranks
      on eligible.dataset_source = ranks.dataset_source
     and eligible.dt = ranks.dt
    {% endif %}
    {% if split_strategy == "bakery_chrono_75_25_test_3mo" %}
    left join bakery_pretest_date_ranks as bakery_pretest_ranks
      on eligible.dataset_source = bakery_pretest_ranks.dataset_source
     and eligible.dt = bakery_pretest_ranks.dt
    {% endif %}
    {% if split_strategy in ["bakery_test_only", "bakery_chrono_75_25_test_3mo"] %}
    cross join bakery_dataset_bounds
    {% endif %}
),
final_panel as (
    select
        base_panel.dataset_source,
        base_panel.source_partition,
        base_panel.source_run_id,
        concat(
            cast(base_panel.dataset_source as varchar),
            '__',
            cast(base_panel.location_id as varchar),
            '__',
            cast(base_panel.product_id as varchar)
        ) as client_id,
        split_labeled.dt,
        split_labeled.target_dt,
        cast(split_labeled.dt as timestamp) + interval 23 hours + interval 59 minutes + interval 59 seconds as decision_timestamp,
        'post_close_d_plus_1' as feature_availability_profile,
        base_panel.location_id,
        base_panel.product_id,
        base_panel.region_id,
        base_panel.org_group_id,
        base_panel.category_level_1,
        base_panel.category_level_2,
        base_panel.category_level_3,
        base_panel.drive_through_flag,
        base_panel.delivery_flag,
        base_panel.pickup_flag,
        base_panel.product_family,
        base_panel.product_subfamily,
        base_panel.is_observed_row,
        base_panel.day_complete_flag,
        base_panel.observed_stockout_flag,
        base_panel.observed_stockout_available,
        base_panel.current_day_demand_qty,
        split_labeled.target_demand_qty_d_plus_1,
        split_labeled.target_delta_log_wow_d_plus_1,
        split_labeled.field_baseline_blend_lag_1_lag_7_d_plus_1,
        split_labeled.target_demand_qty_d_plus_1
            - split_labeled.field_baseline_blend_lag_1_lag_7_d_plus_1
            as target_residual_field_blend_lag_1_lag_7_d_plus_1,
        base_panel.true_zero_demand_flag,
        split_labeled.target_semantics_d_plus_1 as target_semantics,
        split_labeled.censor_flag_d_plus_1 as censor_flag,
        split_labeled.target_source_d_plus_1 as target_source,
        split_labeled.label_quality_score_d_plus_1 as label_quality_score,
        coalesce(split_labeled.target_true_zero_demand_flag, false) as target_true_zero_demand_flag,
        case
            when coalesce(split_labeled.label_quality_score_d_plus_1, 0.0) < 0.75 then false
            when split_labeled.target_source_d_plus_1 in ('closed_or_missing_observation', 'dense_calendar_zero_fill') then false
            else coalesce(split_labeled.usable_for_training_flag_d_plus_1, false)
        end as usable_for_training_flag,
        base_panel.observed_revenue_net,
        base_panel.observed_discount_amount,
        base_panel.promo_flag,
        base_panel.holiday_flag,
        base_panel.activity_flag,
        base_panel.bridge_day_flag,
        base_panel.pre_holiday_flag,
        base_panel.post_holiday_flag,
        base_panel.month_start_flag,
        base_panel.month_end_flag,
        split_labeled.target_holiday_flag,
        base_panel.weather_temperature,
        base_panel.weather_temperature_min,
        base_panel.weather_temperature_max,
        base_panel.weather_precipitation,
        base_panel.weather_humidity,
        base_panel.weather_wind_level,
        base_panel.lending_interest_rate_latest,
        base_panel.vertical_level_1,
        base_panel.vertical_level_2,
        base_panel.country_code,
        base_panel.region_code,
        base_panel.city_name,
        base_panel.source_legal_basis,
        base_panel.source_license_type,
        base_panel.source_review_status,
        base_panel.source_legal_status_snapshot,
        base_panel.source_role,
        base_panel.is_synthetic_source,
        base_panel.gold_run_id,
        split_labeled.lag_1,
        split_labeled.lag_2,
        split_labeled.lag_3,
        split_labeled.lag_4,
        split_labeled.lag_5,
        split_labeled.lag_6,
        split_labeled.lag_7,
        split_labeled.lag_14,
        split_labeled.lag_28,
        split_labeled.target_lag_1,
        split_labeled.target_lag_2,
        split_labeled.target_lag_3,
        split_labeled.target_lag_4,
        split_labeled.target_lag_5,
        split_labeled.target_lag_6,
        split_labeled.target_lag_7,
        split_labeled.target_lag_14,
        split_labeled.target_lag_21,
        split_labeled.target_lag_28,
        split_labeled.rolling_mean_7,
        split_labeled.rolling_mean_14,
        split_labeled.rolling_mean_28,
        split_labeled.rolling_std_28,
        split_labeled.observed_discount_amount_lag_1,
        split_labeled.observed_discount_amount_lag_2,
        split_labeled.observed_discount_amount_lag_3,
        split_labeled.observed_discount_amount_lag_4,
        split_labeled.observed_discount_amount_lag_5,
        split_labeled.observed_discount_amount_lag_6,
        split_labeled.observed_discount_amount_lag_7,
        split_labeled.observed_discount_amount_lag_14,
        split_labeled.observed_discount_amount_lag_28,
        split_labeled.observed_discount_amount_rolling_mean_7,
        split_labeled.observed_discount_amount_rolling_mean_28,
        split_labeled.promo_flag_lag_1,
        split_labeled.promo_flag_lag_2,
        split_labeled.promo_flag_lag_3,
        split_labeled.promo_flag_lag_4,
        split_labeled.promo_flag_lag_5,
        split_labeled.promo_flag_lag_6,
        split_labeled.promo_flag_lag_7,
        split_labeled.promo_flag_lag_14,
        split_labeled.promo_flag_lag_28,
        split_labeled.promo_rate_7,
        split_labeled.promo_rate_28,
        split_labeled.activity_flag_lag_1,
        split_labeled.activity_flag_lag_2,
        split_labeled.activity_flag_lag_3,
        split_labeled.activity_flag_lag_4,
        split_labeled.activity_flag_lag_5,
        split_labeled.activity_flag_lag_6,
        split_labeled.activity_flag_lag_7,
        split_labeled.activity_flag_lag_14,
        split_labeled.activity_flag_lag_28,
        split_labeled.activity_rate_7,
        split_labeled.activity_rate_28,
        split_labeled.observed_stockout_flag_lag_1,
        split_labeled.observed_stockout_flag_lag_2,
        split_labeled.observed_stockout_flag_lag_3,
        split_labeled.observed_stockout_flag_lag_4,
        split_labeled.observed_stockout_flag_lag_5,
        split_labeled.observed_stockout_flag_lag_6,
        split_labeled.observed_stockout_flag_lag_7,
        split_labeled.observed_stockout_flag_lag_14,
        split_labeled.observed_stockout_flag_lag_28,
        split_labeled.observed_stockout_rate_7,
        split_labeled.observed_stockout_rate_28,
        split_labeled.censor_flag_lag_1,
        split_labeled.censor_flag_lag_2,
        split_labeled.censor_flag_lag_3,
        split_labeled.censor_flag_lag_4,
        split_labeled.censor_flag_lag_5,
        split_labeled.censor_flag_lag_6,
        split_labeled.censor_flag_lag_7,
        split_labeled.censor_flag_lag_14,
        split_labeled.censor_flag_lag_28,
        split_labeled.censor_rate_7,
        split_labeled.censor_rate_28,
        split_labeled.label_quality_score_lag_1,
        split_labeled.label_quality_score_lag_2,
        split_labeled.label_quality_score_lag_3,
        split_labeled.label_quality_score_lag_4,
        split_labeled.label_quality_score_lag_5,
        split_labeled.label_quality_score_lag_6,
        split_labeled.label_quality_score_lag_7,
        split_labeled.label_quality_score_lag_14,
        split_labeled.label_quality_score_lag_28,
        split_labeled.label_quality_score_rolling_mean_7,
        split_labeled.label_quality_score_rolling_mean_28,
        split_labeled.day_complete_flag_lag_1,
        split_labeled.day_complete_flag_lag_2,
        split_labeled.day_complete_flag_lag_3,
        split_labeled.day_complete_flag_lag_4,
        split_labeled.day_complete_flag_lag_5,
        split_labeled.day_complete_flag_lag_6,
        split_labeled.day_complete_flag_lag_7,
        split_labeled.day_complete_flag_lag_14,
        split_labeled.day_complete_flag_lag_28,
        split_labeled.day_complete_rate_7,
        split_labeled.day_complete_rate_28,
        split_labeled.same_dow_mean_4w,
        split_labeled.target_same_dow_mean_4w,
        split_labeled.naive_last_value,
        split_labeled.observed_revenue_net_lag_1,
        split_labeled.observed_revenue_net_lag_2,
        split_labeled.observed_revenue_net_lag_3,
        split_labeled.observed_revenue_net_lag_4,
        split_labeled.observed_revenue_net_lag_5,
        split_labeled.observed_revenue_net_lag_6,
        split_labeled.observed_revenue_net_lag_7,
        split_labeled.observed_revenue_net_lag_14,
        split_labeled.observed_revenue_net_lag_28,
        split_labeled.seasonal_naive_d7,
        split_labeled.target_seasonal_naive_d7,
        split_labeled.moving_average_7,
        split_labeled.moving_average_28,
        split_labeled.weather_temperature_lag_0,
        split_labeled.weather_temperature_lag_1,
        split_labeled.weather_temperature_lag_2,
        split_labeled.weather_temperature_lag_3,
        split_labeled.weather_temperature_lag_4,
        split_labeled.weather_temperature_lag_5,
        split_labeled.weather_temperature_lag_6,
        split_labeled.weather_temperature_lag_7,
        split_labeled.weather_temperature_lag_14,
        split_labeled.weather_temperature_rolling_mean_7,
        split_labeled.weather_temperature_rolling_mean_28,
        split_labeled.weather_temperature_min_lag_0,
        split_labeled.weather_temperature_min_lag_1,
        split_labeled.weather_temperature_min_lag_2,
        split_labeled.weather_temperature_min_lag_3,
        split_labeled.weather_temperature_min_lag_4,
        split_labeled.weather_temperature_min_lag_5,
        split_labeled.weather_temperature_min_lag_6,
        split_labeled.weather_temperature_min_lag_7,
        split_labeled.weather_temperature_min_lag_14,
        split_labeled.weather_temperature_max_lag_0,
        split_labeled.weather_temperature_max_lag_1,
        split_labeled.weather_temperature_max_lag_2,
        split_labeled.weather_temperature_max_lag_3,
        split_labeled.weather_temperature_max_lag_4,
        split_labeled.weather_temperature_max_lag_5,
        split_labeled.weather_temperature_max_lag_6,
        split_labeled.weather_temperature_max_lag_7,
        split_labeled.weather_temperature_max_lag_14,
        split_labeled.weather_precipitation_lag_0,
        split_labeled.weather_precipitation_lag_1,
        split_labeled.weather_precipitation_lag_2,
        split_labeled.weather_precipitation_lag_3,
        split_labeled.weather_precipitation_lag_4,
        split_labeled.weather_precipitation_lag_5,
        split_labeled.weather_precipitation_lag_6,
        split_labeled.weather_precipitation_lag_7,
        split_labeled.weather_precipitation_lag_14,
        split_labeled.weather_precipitation_rolling_mean_7,
        split_labeled.weather_precipitation_rolling_mean_28,
        split_labeled.weather_humidity_lag_0,
        split_labeled.weather_humidity_lag_1,
        split_labeled.weather_humidity_lag_2,
        split_labeled.weather_humidity_lag_3,
        split_labeled.weather_humidity_lag_4,
        split_labeled.weather_humidity_lag_5,
        split_labeled.weather_humidity_lag_6,
        split_labeled.weather_humidity_lag_7,
        split_labeled.weather_humidity_lag_14,
        split_labeled.weather_humidity_rolling_mean_7,
        split_labeled.weather_wind_level_lag_0,
        split_labeled.weather_wind_level_lag_1,
        split_labeled.weather_wind_level_lag_2,
        split_labeled.weather_wind_level_lag_3,
        split_labeled.weather_wind_level_lag_4,
        split_labeled.weather_wind_level_lag_5,
        split_labeled.weather_wind_level_lag_6,
        split_labeled.weather_wind_level_lag_7,
        split_labeled.weather_wind_level_lag_14,
        split_labeled.weather_wind_level_rolling_mean_7,
        split_labeled.lending_interest_rate_latest_lag_28,
        split_labeled.target_day_of_week,
        split_labeled.target_day_of_month,
        split_labeled.target_week_of_year,
        split_labeled.target_month,
        split_labeled.target_quarter,
        split_labeled.target_year,
        split_labeled.history_available_days,
        split_labeled.cold_start_bucket,
        split_labeled.target_weekend_flag,
        split_labeled.sin_target_day_of_week,
        split_labeled.cos_target_day_of_week,
        split_labeled.sin_target_week_of_year,
        split_labeled.cos_target_week_of_year,
        split_labeled.sin_target_month,
        split_labeled.cos_target_month,
        split_labeled.split_bucket
    from base_panel
    inner join split_labeled
      on base_panel.dataset_source = split_labeled.dataset_source
     and base_panel.dt = split_labeled.dt
     and base_panel.location_id = split_labeled.location_id
     and base_panel.product_id = split_labeled.product_id
)
select
    *
from final_panel
where split_bucket is not null
{% endmacro %}
