[project]
name = "research-praedixa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "dbt-duckdb>=1.9.4",
    "datasets>=4.8.4",
    "dask[distributed]>=2024.12.1",
    "duckdb>=1.4.1",
    "matplotlib>=3.10.7",
    "numpy>=2.4.4",
    "optuna>=4.8.0",
    "pandas>=3.0.2",
    "polars>=1.33.1",
    "psycopg[binary]>=3.2.9",
    "pyarrow>=23.0.1",
    "pyyaml>=6.0.2",
    "scikit-learn>=1.7.2",
    "sqlalchemy>=2.0.44",
    "xgboost>=3.2.0",
    "openpyxl>=3.1.5",
    "ucimlrepo>=0.0.7",
    "torch>=2.11.0",
    "lightning>=2.6.1",
    "pytorch-forecasting>=1.7.0",
]

[project.optional-dependencies]
tft = [
    "lightning>=2.6.0",
    "pytorch-forecasting>=1.6.0",
    "torch>=2.9.0",
    "torchmetrics>=1.8.0",
]

[dependency-groups]
dev = [
    "pandas-stubs>=3.0.0.260204",
]
