from __future__ import annotations

from typing import Literal


TFTColumnRole = Literal[
    "group_id",
    "date",
    "target",
    "exclude",
    "static_categorical",
    "static_real",
    "time_varying_known_categorical",
    "time_varying_known_real",
    "time_varying_unknown_categorical",
    "time_varying_unknown_real",
]

FEATURE_ROLE_ORDER: tuple[TFTColumnRole, ...] = (
    "static_categorical",
    "static_real",
    "time_varying_known_categorical",
    "time_varying_known_real",
    "time_varying_unknown_categorical",
    "time_varying_unknown_real",
)

EXCLUDED_FROM_TFT_LAG_COLUMNS: tuple[str, ...] = (
    "promo_flag_lag_1",
    "promo_flag_lag_7",
    "promo_flag_lag_28",
    "activity_flag_lag_1",
    "activity_flag_lag_7",
    "activity_flag_lag_28",
    "observed_stockout_flag_lag_1",
    "observed_stockout_flag_lag_7",
    "observed_stockout_flag_lag_28",
    "weather_temperature_lag_0",
    "weather_temperature_lag_1",
    "weather_temperature_lag_7",
    "weather_temperature_min_lag_0",
    "weather_temperature_min_lag_1",
    "weather_temperature_min_lag_7",
    "weather_temperature_max_lag_0",
    "weather_temperature_max_lag_1",
    "weather_temperature_max_lag_7",
    "weather_precipitation_lag_0",
    "weather_precipitation_lag_1",
    "weather_precipitation_lag_7",
    "weather_humidity_lag_0",
    "weather_humidity_lag_1",
    "weather_humidity_lag_7",
    "weather_wind_level_lag_0",
    "weather_wind_level_lag_1",
    "weather_wind_level_lag_7",
    "lending_interest_rate_latest_lag_28",
    "lag_1",
    "lag_7",
    "lag_14",
    "lag_28",
    "target_lag_7",
    "target_lag_14",
    "target_lag_21",
    "target_lag_28",
    "avg_selling_price_lag_1",
    "avg_selling_price_lag_7",
    "avg_selling_price_lag_28",
    "observed_discount_amount_lag_1",
    "observed_discount_amount_lag_7",
    "observed_discount_amount_lag_28",
    "naive_last_value",
    "seasonal_naive_d7",
    "target_seasonal_naive_d7",
    "moving_average_7",
    "moving_average_28",
)

NON_FEATURE_COLUMN_ROLES: dict[str, TFTColumnRole] = {
    **{column: "exclude" for column in EXCLUDED_FROM_TFT_LAG_COLUMNS},
    "__tft_group_id": "exclude",
    "__tft_split": "exclude",
    "__tft_time_idx": "exclude",
    "__tft_sample_weight": "exclude",
    "__tft_prediction_row_id": "exclude",
    "dt": "date",
    "target": "target",
    "target_dt": "exclude",
    "split_bucket": "exclude",
    "target_demand_qty_d_plus_1": "target",
    "target_delta_log_wow_d_plus_1": "exclude",
    "rn_sample": "exclude",
    "source_legal_basis": "exclude",
    "source_license_type": "exclude",
    "source_review_status": "exclude",
    "source_legal_status_snapshot": "exclude",
    "stratum_row_count": "exclude",
    "sample_weight_source": "exclude",
    "sample_weight_business": "exclude",
    "is_primary_eval_dataset": "exclude",
    "gold_run_id": "exclude",
}

TFT_GROUP_ID_COLUMNS: tuple[str, ...] = ("series_id",)

TFT_STATIC_CATEGORICAL_COLUMNS: tuple[str, ...] = (
    "dataset_source",
    "client_id",
    "vertical_level_1",
    "vertical_level_2",
    "country_code",
    "region_code",
    "city_name",
    "site_format",
    "service_model",
    "drive_through_flag",
    "delivery_flag",
    "pickup_flag",
    "late_night_flag",
    "trade_area_type",
    "office_density_bucket",
    "residential_density_bucket",
    "competition_intensity_bucket",
    "product_family",
    "product_subfamily",
    "menu_role",
    "price_band",
    "location_id",
    "product_id",
    "category_level_1",
    "category_level_2",
    "category_level_3",
)

TFT_STATIC_REAL_COLUMNS: tuple[str, ...] = ()

TFT_TIME_VARYING_KNOWN_CATEGORICAL_COLUMNS: tuple[str, ...] = (
    "cold_start_bucket",
    "is_observed_row",
    "true_zero_demand_flag",
    "location_closed_flag",
    "location_open_flag",
    "product_active_flag",
    "day_complete_flag",
    "missing_sales_flag",
    "observed_stockout_flag",
    "observed_stockout_available",
    "anomaly_flag",
    "freshretail_rescaled_flag",
    "target_scale_assumption",
    "promo_flag",
    "price_available",
    "activity_flag",
    "target_day_of_week",
    "target_day_of_month",
    "target_week_of_year",
    "target_month",
    "target_quarter",
    "target_year",
    "current_holiday_flag",
    "current_holiday_name",
    "current_school_holiday_flag",
    "current_school_holiday_name",
    "current_holiday_name_local",
    "school_holiday_flag_local",
    "current_school_holiday_name_local",
    "payday_flag",
    "month_start_flag",
    "month_end_flag",
    "target_weekend_flag",
    "target_holiday_flag",
    "target_holiday_name",
    "target_school_holiday_flag",
    "target_school_holiday_name",
)

TFT_TIME_VARYING_KNOWN_REAL_COLUMNS: tuple[str, ...] = (
    "history_available_days",
    "data_quality_metadata_unavailable_count",
    "data_quality_metadata_missing_count",
    "data_quality_pricing_promo_unavailable_count",
    "data_quality_pricing_promo_missing_count",
    "data_quality_weather_unavailable_count",
    "data_quality_weather_missing_count",
    "data_quality_macro_unavailable_count",
    "data_quality_macro_missing_count",
    "data_quality_operations_unavailable_count",
    "data_quality_operations_missing_count",
    "data_quality_history_unavailable_count",
    "data_quality_history_missing_count",
    "current_day_demand_qty",
    "avg_selling_price",
    "observed_discount_amount",
    "sin_target_day_of_week",
    "cos_target_day_of_week",
    "sin_target_week_of_year",
    "cos_target_week_of_year",
    "sin_target_month",
    "cos_target_month",
    "weather_temperature_rolling_mean_7",
    "weather_temperature_rolling_mean_28",
    "weather_precipitation_rolling_mean_7",
    "weather_precipitation_rolling_mean_28",
    "weather_humidity_rolling_mean_7",
    "weather_wind_level_rolling_mean_7",
    "weather_humidity",
    "weather_wind_level",
    "lending_interest_rate_latest",
    "rolling_mean_7",
    "rolling_mean_14",
    "rolling_mean_28",
    "rolling_std_28",
    "observed_discount_amount_rolling_mean_7",
    "observed_discount_amount_rolling_mean_28",
    "promo_rate_7",
    "promo_rate_28",
    "activity_rate_7",
    "activity_rate_28",
    "observed_stockout_rate_7",
    "observed_stockout_rate_28",
    "same_dow_mean_4w",
    "target_same_dow_mean_4w",
)

TFT_TIME_VARYING_UNKNOWN_CATEGORICAL_COLUMNS: tuple[str, ...] = ()
TFT_TIME_VARYING_UNKNOWN_REAL_COLUMNS: tuple[str, ...] = ()
