from __future__ import annotations

from praedixa.demand_forecast.contracts.targets import DEFAULT_VARIATION_TARGET_COL
from praedixa.platform.runtime.paths import LOCAL_DUCKDB_PATH
from praedixa.platform.runtime.paths import OPTIMISATION_DIR


DEFAULT_DUCKDB_PATH = LOCAL_DUCKDB_PATH
DEFAULT_GOLD_TABLE = "gold.gold_daily_product_forecast_panel_d1"
DEFAULT_TRAIN_INPUT_PATH = None
DEFAULT_TUNING_INPUT_PATH = None
DEFAULT_OUTPUT_DIR = OPTIMISATION_DIR
DEFAULT_TARGET_COL = DEFAULT_VARIATION_TARGET_COL
DEFAULT_DATE_COL = "dt"
DEFAULT_DATASET_SOURCE_COL = "dataset_source"
DEFAULT_SAMPLE_STORE_COL = "location_id"
DEFAULT_TRAIN_SAMPLE_FRACTION = 0.10
DEFAULT_TUNING_SAMPLE_FRACTION = 0.10
DEFAULT_MIN_SAMPLES_PER_DATASET = 1000
DEFAULT_MAX_PARALLEL_FOLD_WORKERS = 5
DEFAULT_TARGET_TRANSFORM = "log1p"
DEFAULT_N_FOLDS = 5
DEFAULT_TUNING_TRIALS = 100
DEFAULT_TUNING_RANDOM_SEED = 42
DEFAULT_TUNING_PROGRESS_LOG_EVERY = 10
DEFAULT_STAGE_BUDGET = "standard"
DEFAULT_OPTIMISATION_MAIN_RUNTIME_PROFILE = "local_cpu"
DEFAULT_OPTIMISATION_MAIN_N_FOLDS = DEFAULT_N_FOLDS
DEFAULT_OPTIMISATION_MAIN_MAX_TRIALS = DEFAULT_TUNING_TRIALS
DEFAULT_OPTIMISATION_MAIN_STAGE_BUDGET = DEFAULT_STAGE_BUDGET
DEFAULT_OPTIMISATION_MAIN_TRAIN_SAMPLE_FRACTION = 0.10
DEFAULT_OPTIMISATION_MAIN_TUNING_SAMPLE_FRACTION = 0.10
DEFAULT_H100_OPTIMISATION_MAIN_N_FOLDS = 5
DEFAULT_H100_OPTIMISATION_MAIN_MAX_TRIALS = 192
DEFAULT_H100_OPTIMISATION_MAIN_STAGE_BUDGET = "full"
DEFAULT_H100_OPTIMISATION_MAIN_TRAIN_SAMPLE_FRACTION = 0.10
DEFAULT_H100_OPTIMISATION_MAIN_TUNING_SAMPLE_FRACTION = 0.10
DEFAULT_TUNING_BATCH_SIZE_CHOICES = (2048, 4096, 8192)
DEFAULT_TUNING_GPU_BATCH_SIZE_CHOICES = DEFAULT_TUNING_BATCH_SIZE_CHOICES
DEFAULT_TUNING_ENCODER_LENGTH_CHOICES = (7, 14, 28)
DEFAULT_TUNING_GRADIENT_CLIP_CHOICES = (0.05, 0.1, 0.5, 1.0)
DEFAULT_TUNING_HIDDEN_SIZE_CHOICES = (8, 16, 24, 32, 48, 64, 96, 128)
DEFAULT_TUNING_HIDDEN_CONTINUOUS_SIZE_CHOICES = (4, 8, 12, 16, 24, 32, 48, 64)
DEFAULT_TUNING_ATTENTION_HEAD_SIZE_CHOICES = (1, 2, 4)
DEFAULT_TUNING_LSTM_LAYER_CHOICES = (1, 2, 3)
DEFAULT_TUNING_LEARNING_RATE_LOW = 1e-3
DEFAULT_TUNING_LEARNING_RATE_HIGH = 1e-2
DEFAULT_TUNING_LEARNING_RATE_REFERENCE_BATCH_SIZE = 64
DEFAULT_TUNING_MAX_BATCH_SCALED_LEARNING_RATE_SCALE = 4.0
DEFAULT_TUNING_DROPOUT_LOW = 0.05
DEFAULT_TUNING_DROPOUT_HIGH = 0.30
DEFAULT_TUNING_DROPOUT_STAGE_B_MARGIN = 0.08
DEFAULT_TUNING_WEIGHT_DECAY_LOW = 1e-6
DEFAULT_TUNING_WEIGHT_DECAY_HIGH = 1e-2
DEFAULT_TUNING_LR_FINDER_MIN_LR = 1e-5
DEFAULT_TUNING_LR_FINDER_MAX_LR = 1.0
DEFAULT_TUNING_LR_FINDER_NUM_TRAINING = 100
DEFAULT_TUNING_LR_FINDER_EARLY_STOP_THRESHOLD = 10000.0
DEFAULT_TUNING_SAMPLER_STARTUP_TRIALS = 10
DEFAULT_TUNING_ANCHORED_LOG_LOWER_FACTOR = 0.5
DEFAULT_TUNING_ANCHORED_LOG_UPPER_FACTOR = 2.0
DEFAULT_TUNING_STAGE_POLICIES: dict[str, dict[str, object]] = {
    "smoke": {
        "stage_a_ratio": 1.0,
        "stage_a_epoch_range": (2, 2),
        "stage_b_epoch_range": (2, 2),
    },
    "quick": {
        "stage_a_ratio": 0.80,
        "stage_a_epoch_range": (4, 6),
        "stage_b_epoch_range": (8, 12),
    },
    "standard": {
        "stage_a_ratio": 0.70,
        "stage_a_epoch_range": (6, 12),
        "stage_b_epoch_range": (18, 32),
    },
    "full": {
        "stage_a_ratio": 0.60,
        "stage_a_epoch_range": (10, 18),
        "stage_b_epoch_range": (32, 64),
    },
}
DEFAULT_TUNING_PRUNER_CONFIG: dict[str, int | str] = {
    "type": "MedianPruner",
    "n_startup_trials": 4,
    "n_warmup_steps": 2,
    "interval_steps": 1,
}
DEFAULT_TUNING_GUARDRAIL_DATASET_WAPE_COLLAPSE_MULTIPLIER = 1.50
DEFAULT_TUNING_GUARDRAIL_MIN_ABS_BIAS_LIMIT = 0.5
DEFAULT_TUNING_GUARDRAIL_COVERAGE_80_BOUNDS = (0.60, 0.98)
DEFAULT_TUNING_GUARDRAIL_COVERAGE_95_BOUNDS = (0.80, 0.995)
DEFAULT_IDENTIFIER_FEATURE_COLS = (
    "series_id",
    "location_id",
    "product_id",
    "client_id",
    "gold_run_id",
)
DEFAULT_EXCLUDED_RISKY_FEATURE_COLS = (
    "current_day_demand_qty",
    "observed_revenue_net",
    "target_dt",
    "sample_weight_source",
    "sample_weight_business",
    "is_primary_eval_dataset",
    "source_legal_basis",
    "source_license_type",
    "source_review_status",
    "source_legal_status_snapshot",
)
