{{ config(tags=["staging", "supplemental_corpus"]) }}

select
    dataset_source,
    source_partition,
    source_run_id,
    series_id,
    dt,
    location_id,
    product_id,
    region_id,
    org_group_id,
    category_level_1,
    category_level_2,
    category_level_3,
    observed_demand_qty,
    target_semantics,
    censor_flag,
    target_source,
    label_quality_score,
    usable_for_training_flag,
    observed_revenue_net,
    observed_discount_amount,
    promo_flag,
    holiday_flag,
    activity_flag,
    observed_stockout_flag,
    observed_stockout_available,
    observed_stockout_intensity,
    day_complete_flag,
    calendar_weekday_name,
    calendar_day_of_week,
    calendar_month,
    calendar_year,
    calendar_week_key,
    event_name_1,
    event_type_1,
    event_name_2,
    event_type_2,
    weather_precipitation,
    weather_temperature,
    weather_humidity,
    weather_wind_level,
    silver_run_id,
    nullif(cast(source_name as varchar), '') as source_name,
    nullif(cast(source_policy_id as varchar), '') as source_policy_id,
    source_file_path,
    loaded_at
from {{ source('bronze', 'bronze_supplemental_corpus_daily') }}
