{{ config(tags=["silver", "bakery"], unique_key=["dataset_source", "source_partition", "row_index"]) }}

select
    'bakery' as dataset_source,
    source_partition,
    'warehouse_run' as source_run_id,
    concat('bakery_store_1', '__', product_id) as series_id,
    dt,
    'bakery_store_1' as location_id,
    product_id,
    cast(null as varchar) as region_id,
    cast(null as varchar) as org_group_id,
    cast(null as varchar) as category_level_1,
    cast(null as varchar) as category_level_2,
    cast(null as varchar) as category_level_3,
    quantity as observed_demand_qty,
    quantity * unit_price as observed_revenue_net,
    cast(null as double) as observed_discount_amount,
    unit_price as avg_selling_price,
    cast(null as boolean) as promo_flag,
    cast(null as boolean) as holiday_flag,
    cast(null as boolean) as activity_flag,
    cast(null as boolean) as observed_stockout_flag,
    false as observed_stockout_available,
    cast(null as double) as observed_stockout_intensity,
    cast(null as boolean) as location_open_flag,
    cast(null as boolean) as day_complete_flag,
    false as missing_sales_flag,
    strftime(dt, '%A') as calendar_weekday_name,
    cast(strftime(dt, '%u') as integer) - 1 as calendar_day_of_week,
    cast(strftime(dt, '%m') as integer) as calendar_month,
    cast(strftime(dt, '%Y') as integer) as calendar_year,
    cast(strftime(dt, '%V') as integer) as calendar_week_key,
    cast(null as varchar) as event_name_1,
    cast(null as varchar) as event_type_1,
    cast(null as varchar) as event_name_2,
    cast(null as varchar) as event_type_2,
    cast(null as boolean) as snap_flag,
    cast(null as double) as weather_precipitation,
    cast(null as double) as weather_temperature,
    cast(null as double) as weather_humidity,
    cast(null as double) as weather_wind_level,
    false as anomaly_flag,
    '{{ env_var("PRAEDIXA_SILVER_RUN_ID", "manual") }}' as silver_run_id,
    row_index,
    ticket_number_raw,
    sold_at_local_ts
from {{ ref("stg_bakery_order_lines") }}
