from __future__ import annotations

from praedixa.demand_forecast.backends.tft.model_utils import DEFAULT_TFT_MODEL_PARAMS
from praedixa.platform.runtime.paths import FEATURE_SELECTION_DIR
from praedixa.platform.runtime.paths import LOCAL_DUCKDB_PATH


DEFAULT_INPUT_PATH = None
DEFAULT_OUTPUT_DIR = FEATURE_SELECTION_DIR
DEFAULT_DUCKDB_PATH = LOCAL_DUCKDB_PATH
DEFAULT_GOLD_TABLE = "gold.gold_daily_product_forecast_panel_d1"
DEFAULT_TARGET_COL = "target"
DEFAULT_DATE_COL = "dt"
DEFAULT_TRAIN_FRACTION = 0.7
DEFAULT_N_FOLDS = 5
DEFAULT_PEARSON_THRESHOLD = 0.95
DEFAULT_SPEARMAN_THRESHOLD = 0.95
DEFAULT_TUNING_TRIALS = 50
DEFAULT_RANDOM_SEED = 42
DEFAULT_EARLY_STOPPING_ROUNDS = 100
DEFAULT_LAG_PATTERNS = ("_lag_", "_rolling_", "_ewm_")
DEFAULT_PROGRESS_LOG_EVERY = 25
DEFAULT_TUNING_PROGRESS_LOG_EVERY = 10
DEFAULT_MEMMAP_PROGRESS_LOG_EVERY = 25
DEFAULT_CORRELATION_PROGRESS_LOG_EVERY = 25
DEFAULT_CORRELATION_ONLY = False
DEFAULT_MAX_SELECTED_LAG_FEATURES: int | None = None
DEFAULT_MODEL_PARAMS = {**DEFAULT_TFT_MODEL_PARAMS}
