{{ config(tags=["gold", "d1"], materialized="view", schema=env_var("PRAEDIXA_DUCKDB_GOLD_SCHEMA", "gold")) }}

with features as (
    select *
    from {{ ref("gold_feature_panel_d1") }}
),
source_weights as (
    select *
    from {{ ref("gold_source_weights_d1") }}
)
select
    features.dataset_source,
    features.client_id,
    features.vertical_level_1,
    features.vertical_level_2,
    features.country_code,
    features.region_code,
    features.city_name,
    features.series_id,
    features.location_id,
    features.product_id,
    features.category_level_1,
    features.category_level_2,
    features.category_level_3,
    features.dt,
    features.target_dt,
    features.split_bucket,
    features.target_demand_qty_d_plus_1,
    features.target_delta_log_wow_d_plus_1,
    features.current_day_demand_qty,
    features.is_observed_row,
    features.true_zero_demand_flag,
    features.location_closed_flag,
    features.location_open_flag,
    features.product_active_flag,
    features.day_complete_flag,
    features.missing_sales_flag,
    features.observed_stockout_flag,
    features.observed_stockout_available,
    features.anomaly_flag,
    features.freshretail_rescaled_flag,
    features.target_scale_assumption,
    features.avg_selling_price,
    features.observed_discount_amount,
    features.promo_flag,
    features.price_available,
    features.activity_flag,
    features.target_day_of_week,
    features.target_day_of_month,
    features.target_week_of_year,
    features.target_month,
    features.target_quarter,
    features.target_year,
    features.current_holiday_flag,
    features.current_holiday_name,
    features.current_school_holiday_flag,
    features.current_bridge_day_flag,
    features.current_pre_holiday_flag,
    features.current_post_holiday_flag,
    features.target_weekend_flag,
    features.target_holiday_flag,
    features.target_holiday_name,
    features.target_school_holiday_flag,
    features.target_bridge_day_flag,
    features.target_pre_holiday_flag,
    features.target_post_holiday_flag,
    features.sin_target_day_of_week,
    features.cos_target_day_of_week,
    features.sin_target_week_of_year,
    features.cos_target_week_of_year,
    features.sin_target_month,
    features.cos_target_month,
    features.snap_flag,
    features.weather_temperature_lag_0,
    features.weather_temperature_lag_1,
    features.weather_temperature_lag_7,
    features.weather_temperature_rolling_mean_7,
    features.weather_temperature_rolling_mean_28,
    features.weather_temperature_min_lag_1,
    features.weather_temperature_min_lag_7,
    features.weather_temperature_min_rolling_mean_7,
    features.weather_temperature_max_lag_1,
    features.weather_temperature_max_lag_7,
    features.weather_temperature_max_rolling_mean_7,
    features.weather_temperature_min,
    features.weather_temperature_max,
    features.weather_precipitation_lag_0,
    features.weather_precipitation_lag_1,
    features.weather_precipitation_lag_7,
    features.weather_precipitation_rolling_mean_7,
    features.weather_precipitation_rolling_mean_28,
    features.weather_humidity_lag_0,
    features.weather_humidity_lag_1,
    features.weather_humidity_lag_7,
    features.weather_humidity_rolling_mean_7,
    features.weather_wind_level_lag_0,
    features.weather_wind_level_lag_1,
    features.weather_wind_level_lag_7,
    features.weather_wind_level_rolling_mean_7,
    features.weather_humidity,
    features.weather_wind_level,
    features.weather_available,
    features.inflation_cpi_latest,
    features.inflation_cpi_latest_lag_28,
    features.inflation_cpi_latest_delta_28,
    features.food_cpi_latest,
    features.food_cpi_latest_lag_28,
    features.food_cpi_latest_delta_28,
    features.policy_rate_latest,
    features.policy_rate_latest_lag_28,
    features.policy_rate_latest_delta_28,
    features.unemployment_rate_latest,
    features.unemployment_rate_latest_lag_28,
    features.unemployment_rate_latest_delta_28,
    features.consumer_confidence_latest,
    features.consumer_confidence_latest_lag_28,
    features.consumer_confidence_latest_delta_28,
    features.retail_sales_index_latest,
    features.retail_sales_index_latest_lag_28,
    features.retail_sales_index_latest_delta_28,
    features.gdp_quarterly_level_latest,
    features.gdp_quarterly_level_latest_lag_28,
    features.gdp_quarterly_level_latest_delta_28,
    features.gdp_growth_latest,
    features.gdp_growth_latest_lag_28,
    features.gdp_growth_latest_delta_28,
    features.gdp_current_usd_latest,
    features.gdp_current_usd_latest_lag_28,
    features.gdp_current_usd_latest_delta_28,
    features.lending_interest_rate_latest,
    features.lending_interest_rate_latest_lag_28,
    features.lending_interest_rate_latest_delta_28,
    features.government_debt_pct_gdp_latest,
    features.government_debt_pct_gdp_latest_lag_28,
    features.government_debt_pct_gdp_latest_delta_28,
    features.macro_available,
    features.lag_1,
    features.lag_7,
    features.lag_14,
    features.lag_28,
    features.target_lag_7,
    features.target_lag_14,
    features.target_lag_21,
    features.target_lag_28,
    features.rolling_mean_7,
    features.rolling_mean_14,
    features.rolling_mean_28,
    features.rolling_std_28,
    features.avg_selling_price_lag_1,
    features.avg_selling_price_lag_7,
    features.avg_selling_price_lag_28,
    features.avg_selling_price_rolling_mean_7,
    features.avg_selling_price_rolling_mean_28,
    features.observed_discount_amount_lag_1,
    features.observed_discount_amount_lag_7,
    features.observed_discount_amount_lag_28,
    features.observed_discount_amount_rolling_mean_7,
    features.observed_discount_amount_rolling_mean_28,
    features.promo_flag_lag_1,
    features.promo_flag_lag_7,
    features.promo_flag_lag_28,
    features.promo_rate_7,
    features.promo_rate_28,
    features.activity_flag_lag_1,
    features.activity_flag_lag_7,
    features.activity_flag_lag_28,
    features.activity_rate_7,
    features.activity_rate_28,
    features.observed_stockout_flag_lag_1,
    features.observed_stockout_flag_lag_7,
    features.observed_stockout_flag_lag_28,
    features.observed_stockout_rate_7,
    features.observed_stockout_rate_28,
    features.same_dow_mean_4w,
    features.target_same_dow_mean_4w,
    features.naive_last_value,
    features.seasonal_naive_d7,
    features.target_seasonal_naive_d7,
    features.moving_average_7,
    features.moving_average_28,
    source_weights.sample_weight_source,
    1.0 as sample_weight_business,
    features.dataset_source = 'bakery' as is_primary_eval_dataset,
    features.gold_run_id
from (
    select
        *,
        holiday_flag as current_holiday_flag,
        holiday_name as current_holiday_name,
        school_holiday_flag as current_school_holiday_flag,
        bridge_day_flag as current_bridge_day_flag,
        pre_holiday_flag as current_pre_holiday_flag,
        post_holiday_flag as current_post_holiday_flag
    from features
) as features
inner join source_weights
  on features.split_bucket = source_weights.split_bucket
 and features.dataset_source = source_weights.dataset_source
